import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
export const metadata = {
  title: 'SNL Alumni Universe',
  description: 'Explore Saturday Night Live alumni connections.',
  verification: {
    google: 'S3TJp5OcNO1_IcflO0zqjELpP8aPwjWNqXOnmLG7QG4',
  },
};
export const metadata = {
  title: 'SNL Alumni Universe',
  description: 'Explore Saturday Night Live alumni connections.',
  verification: {
    google: 'S3TJp5OcNO1_IcflO0zqjELpP8aPwjWNqXOnmLG7QG4',
  },
};
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
