export type UniverseNodeType = 'alumni' | 'movie' | 'tv' | 'character' | 'creator' | 'award';

export type UniverseNode = {
  id: string;
  name: string;
  type: UniverseNodeType;
  years?: string;
  role?: string;
  bio: string;
  imageTone: string;
  tags: string[];
  highlights: string[];
  catchphrases?: string[];
  awards?: string[];
};

export type UniverseEdge = {
  source: string;
  target: string;
  relation: string;
  project?: string;
  strength: number;
};

export type TimelineMoment = {
  year: string;
  title: string;
  detail: string;
  era: string;
};

export type TriviaQuestion = {
  prompt: string;
  answer: string;
  options: string[];
};

export const universeNodes: UniverseNode[] = [
  // ── The institution ─────────────────────────────────────────────
  {
    id: 'snl',
    name: 'Saturday Night Live',
    type: 'tv',
    years: '1975-present',
    role: 'NBC sketch institution',
    bio: 'The live comedy engine that connects generations of performers, writers, hosts, musicians, and recurring characters.',
    imageTone: 'from-slate-900 via-red-700 to-amber-300',
    tags: ['Sketches', 'Weekend Update', 'Live TV'],
    highlights: ['Late-night comedy launchpad', 'Political satire archive', 'Recurring character factory'],
  },

  // ── Alumni ──────────────────────────────────────────────────────
  {
    id: 'bill-murray',
    name: 'Bill Murray',
    type: 'alumni',
    years: '1977-1980',
    role: 'Cast member',
    bio: 'Deadpan SNL star who became a film icon through comedy, melancholy, and collaborations spanning Ghostbusters to Wes Anderson.',
    imageTone: 'from-sky-800 via-cyan-600 to-amber-200',
    tags: ['Deadpan', 'Film icon', 'Original era'],
    highlights: ['Nick the Lounge Singer', 'Ghostbusters', 'Lost in Translation'],
    catchphrases: ['No one will ever believe you.'],
    awards: ['Emmy Award', 'Golden Globe'],
  },
  {
    id: 'dan-aykroyd',
    name: 'Dan Aykroyd',
    type: 'alumni',
    years: '1975-1979',
    role: 'Cast member and writer',
    bio: 'Original cast powerhouse whose characters and genre instincts helped bridge SNL sketches and blockbuster comedy.',
    imageTone: 'from-indigo-950 via-blue-600 to-lime-300',
    tags: ['Original cast', 'Writer', 'Blues Brothers'],
    highlights: ['Coneheads', 'The Blues Brothers', 'Ghostbusters'],
    awards: ['Emmy Award'],
  },
  {
    id: 'eddie-murphy',
    name: 'Eddie Murphy',
    type: 'alumni',
    years: '1980-1984',
    role: 'Cast member',
    bio: 'A breakout force who reshaped the early 1980s cast and carried SNL energy into stand-up, film, and character comedy.',
    imageTone: 'from-purple-950 via-fuchsia-700 to-yellow-300',
    tags: ['Character comedy', 'Stand-up', 'Movie star'],
    highlights: ['Mister Robinson', 'Gumby', 'Beverly Hills Cop'],
    catchphrases: ['I am Gumby, dammit.'],
    awards: ['Emmy Award', 'Golden Globe', 'Mark Twain Prize'],
  },
  {
    id: 'tina-fey',
    name: 'Tina Fey',
    type: 'alumni',
    years: '1997-2006',
    role: 'Writer, head writer, cast member',
    bio: 'Head writer and Weekend Update anchor whose SNL voice expanded into sitcoms, films, political impressions, and producer-led comedy.',
    imageTone: 'from-emerald-950 via-teal-600 to-rose-300',
    tags: ['Head writer', 'Weekend Update', 'Producer'],
    highlights: ['Weekend Update', '30 Rock', 'Mean Girls'],
    catchphrases: ['I want to go to there.'],
    awards: ['Emmy Awards', 'Mark Twain Prize'],
  },
  {
    id: 'amy-poehler',
    name: 'Amy Poehler',
    type: 'alumni',
    years: '2001-2008',
    role: 'Cast member and Weekend Update anchor',
    bio: 'High-energy performer and improviser whose SNL run connects to Upright Citizens Brigade, Parks and Recreation, and broad ensemble comedy.',
    imageTone: 'from-red-950 via-orange-600 to-cyan-200',
    tags: ['Improv', 'Weekend Update', 'Ensemble comedy'],
    highlights: ['Weekend Update', 'Parks and Recreation', 'Baby Mama'],
    awards: ['Golden Globe'],
  },
  {
    id: 'maya-rudolph',
    name: 'Maya Rudolph',
    type: 'alumni',
    years: '2000-2007',
    role: 'Cast member',
    bio: 'A musical, elastic performer with a rare range across impressions, ensemble films, voice work, and prestige comedy.',
    imageTone: 'from-zinc-900 via-pink-700 to-green-300',
    tags: ['Impressions', 'Music', 'Voice acting'],
    highlights: ['Donatella Versace', 'Bridesmaids', 'Big Mouth'],
    awards: ['Emmy Awards'],
  },
  {
    id: 'adam-sandler',
    name: 'Adam Sandler',
    type: 'alumni',
    years: '1990-1995',
    role: 'Cast member and writer',
    bio: 'Musical sketch oddball turned box-office comedy anchor, with a collaboration network that became its own comedy ecosystem.',
    imageTone: 'from-blue-950 via-violet-700 to-orange-300',
    tags: ['Songs', '90s cast', 'Film franchise'],
    highlights: ['The Chanukah Song', 'Happy Gilmore', 'Grown Ups'],
    catchphrases: ['The price is wrong.'],
    awards: ['Independent Spirit Award', 'Mark Twain Prize'],
  },
  {
    id: 'chris-rock',
    name: 'Chris Rock',
    type: 'alumni',
    years: '1990-1993',
    role: 'Cast member',
    bio: 'Sharp stand-up voice whose SNL orbit links political comedy, film ensembles, HBO specials, and modern comedy influence.',
    imageTone: 'from-stone-950 via-red-800 to-sky-300',
    tags: ['Stand-up', 'Commentary', 'Film'],
    highlights: ['New Jack City', 'Everybody Hates Chris', 'Grown Ups'],
    awards: ['Emmy Awards', 'Grammy Awards'],
  },
  {
    id: 'andy-samberg',
    name: 'Andy Samberg',
    type: 'alumni',
    years: '2005-2012',
    role: 'Cast member and digital short creator',
    bio: 'Digital-era star who helped make SNL clips native to the internet, then carried that rhythm into sitcoms and music comedy.',
    imageTone: 'from-cyan-950 via-blue-500 to-yellow-200',
    tags: ['Digital shorts', 'Music comedy', 'Brooklyn Nine-Nine'],
    highlights: ['Lazy Sunday', 'The Lonely Island', 'Brooklyn Nine-Nine'],
    awards: ['Golden Globe', 'Emmy Award'],
  },
  {
    id: 'kristen-wiig',
    name: 'Kristen Wiig',
    type: 'alumni',
    years: '2005-2012',
    role: 'Cast member',
    bio: 'Character-driven performer who turned awkwardness, commitment, and ensemble chemistry into a modern SNL signature.',
    imageTone: 'from-neutral-950 via-emerald-700 to-pink-200',
    tags: ['Characters', 'Film writing', 'Ensemble'],
    highlights: ['Target Lady', 'Bridesmaids', 'MacGruber'],
    awards: ['Oscar nomination', 'Emmy nominations'],
  },
  {
    id: 'will-ferrell',
    name: 'Will Ferrell',
    type: 'alumni',
    years: '1995-2002',
    role: 'Cast member',
    bio: 'A maximalist sketch performer whose SNL characters fed directly into a run of dominant studio comedies.',
    imageTone: 'from-amber-950 via-red-600 to-sky-200',
    tags: ['Physical comedy', 'Characters', 'Studio comedy'],
    highlights: ['Celebrity Jeopardy', 'More Cowbell', 'Anchorman'],
    catchphrases: ['More cowbell.'],
    awards: ['Mark Twain Prize'],
  },
  {
    id: 'chevy-chase',
    name: 'Chevy Chase',
    type: 'alumni',
    years: '1975-1976',
    role: 'Cast member and Weekend Update anchor',
    bio: 'Original cast member whose Weekend Update persona and film career helped define the first SNL-to-movies pathway.',
    imageTone: 'from-zinc-950 via-stone-600 to-yellow-200',
    tags: ['Original cast', 'Weekend Update', 'Film comedy'],
    highlights: ['Weekend Update', 'Caddyshack', 'National Lampoon’s Vacation'],
    catchphrases: ['Good evening, I’m Chevy Chase, and you’re not.'],
    awards: ['Emmy Award'],
  },
  {
    id: 'john-belushi',
    name: 'John Belushi',
    type: 'alumni',
    years: '1975-1979',
    role: 'Cast member',
    bio: 'Original cast phenomenon whose physical intensity and music-comedy work helped turn SNL characters into cultural events.',
    imageTone: 'from-neutral-950 via-red-800 to-sky-200',
    tags: ['Original cast', 'Physical comedy', 'Blues Brothers'],
    highlights: ['Samurai Futaba', 'The Blues Brothers', 'Animal House'],
  },
  {
    id: 'gilda-radner',
    name: 'Gilda Radner',
    type: 'alumni',
    years: '1975-1980',
    role: 'Cast member',
    bio: 'Beloved original cast member whose characters made emotional specificity and joyful absurdity central to SNL.',
    imageTone: 'from-rose-950 via-pink-600 to-amber-200',
    tags: ['Original cast', 'Characters', 'Sketch icon'],
    highlights: ['Roseanne Roseannadanna', 'Emily Litella', 'Baba Wawa'],
    catchphrases: ['Never mind.'],
    awards: ['Emmy Award'],
  },
  {
    id: 'dana-carvey',
    name: 'Dana Carvey',
    type: 'alumni',
    years: '1986-1993',
    role: 'Cast member',
    bio: 'Master impressionist and character comedian whose SNL run linked political satire, recurring characters, and breakout sketch films.',
    imageTone: 'from-blue-950 via-indigo-600 to-amber-200',
    tags: ['Impressions', 'Characters', 'Wayne’s World'],
    highlights: ['The Church Lady', 'George H. W. Bush', 'Wayne’s World'],
    catchphrases: ['Well, isn’t that special?'],
    awards: ['Emmy Award'],
  },
  {
    id: 'mike-myers',
    name: 'Mike Myers',
    type: 'alumni',
    years: '1989-1995',
    role: 'Cast member and writer',
    bio: 'Character architect whose SNL creations became film franchises and a durable language of 1990s comedy.',
    imageTone: 'from-slate-950 via-cyan-700 to-orange-200',
    tags: ['Characters', 'Film franchise', 'Writer-performer'],
    highlights: ['Wayne’s World', 'Austin Powers', 'Shrek'],
    catchphrases: ['Party on.'],
  },
  {
    id: 'molly-shannon',
    name: 'Molly Shannon',
    type: 'alumni',
    years: '1995-2001',
    role: 'Cast member',
    bio: 'Fearless physical comedian whose characters helped establish the late-1990s cast as a new character-comedy engine.',
    imageTone: 'from-red-950 via-orange-600 to-pink-200',
    tags: ['Physical comedy', 'Characters', '90s cast'],
    highlights: ['Mary Katherine Gallagher', 'Superstar', 'The Delicious Dish'],
  },
  {
    id: 'jimmy-fallon',
    name: 'Jimmy Fallon',
    type: 'alumni',
    years: '1998-2004',
    role: 'Cast member and Weekend Update anchor',
    bio: 'Impressionist, musical performer, and Update anchor who later became a major late-night host.',
    imageTone: 'from-sky-950 via-blue-600 to-white',
    tags: ['Weekend Update', 'Music comedy', 'Late night'],
    highlights: ['Weekend Update', 'Barry Gibb Talk Show', 'The Tonight Show'],
    awards: ['Emmy Award'],
  },
  {
    id: 'seth-meyers',
    name: 'Seth Meyers',
    type: 'alumni',
    years: '2001-2014',
    role: 'Cast member, head writer, Weekend Update anchor',
    bio: 'Longtime writer-performer and Update anchor whose SNL voice continued into late-night political comedy.',
    imageTone: 'from-indigo-950 via-slate-600 to-cyan-200',
    tags: ['Head writer', 'Weekend Update', 'Late night'],
    highlights: ['Weekend Update', 'Really!?!', 'Late Night'],
    awards: ['Emmy Award'],
  },
  {
    id: 'bill-hader',
    name: 'Bill Hader',
    type: 'alumni',
    years: '2005-2013',
    role: 'Cast member',
    bio: 'Impressionist and character performer whose SNL work bridged surreal Update characters, cinema, and prestige comedy.',
    imageTone: 'from-violet-950 via-purple-700 to-lime-200',
    tags: ['Impressions', 'Characters', 'Prestige comedy'],
    highlights: ['Stefon', 'Vinny Vedecci', 'Barry'],
    awards: ['Emmy Awards'],
  },
  {
    id: 'kate-mckinnon',
    name: 'Kate McKinnon',
    type: 'alumni',
    years: '2012-2022',
    role: 'Cast member',
    bio: 'Transformational impressionist and character performer who became one of the defining cast members of the 2010s.',
    imageTone: 'from-teal-950 via-emerald-600 to-violet-200',
    tags: ['Impressions', 'Characters', '2010s cast'],
    highlights: ['Hillary Clinton', 'Ruth Bader Ginsburg', 'Close Encounter'],
    awards: ['Emmy Awards'],
  },
  {
    id: 'kenan-thompson',
    name: 'Kenan Thompson',
    type: 'alumni',
    years: '2003-present',
    role: 'Cast member',
    bio: 'SNL’s longest-serving cast member, known for anchoring sketches across multiple eras with warmth, timing, and range.',
    imageTone: 'from-amber-950 via-yellow-700 to-cyan-200',
    tags: ['Longest-serving cast', 'Characters', 'Modern era'],
    highlights: ['What Up With That', 'Family Feud', 'Kenan'],
    awards: ['Emmy Award'],
  },
  {
    id: 'fred-armisen',
    name: 'Fred Armisen',
    type: 'alumni',
    years: '2002-2013',
    role: 'Cast member',
    bio: 'Musical and observational sketch performer whose SNL sensibility extended into Portlandia and character-driven satire.',
    imageTone: 'from-stone-950 via-emerald-800 to-rose-200',
    tags: ['Music comedy', 'Characters', 'Alternative comedy'],
    highlights: ['Fericito', 'Portlandia', 'Documentary Now!'],
    awards: ['Peabody Award'],
  },
  {
    id: 'phil-hartman',
    name: 'Phil Hartman',
    type: 'alumni',
    years: '1986-1994',
    role: 'Cast member',
    bio: 'Nicknamed "The Glue" for holding sketches together, a versatile impressionist whose reliability anchored a golden era of the show.',
    imageTone: 'from-slate-950 via-blue-800 to-amber-200',
    tags: ['Impressions', 'Utility player', '90s cast'],
    highlights: ['Unfrozen Caveman Lawyer', 'Bill Clinton', 'NewsRadio'],
    awards: ['Emmy Award'],
  },
  {
    id: 'chris-farley',
    name: 'Chris Farley',
    type: 'alumni',
    years: '1990-1995',
    role: 'Cast member',
    bio: 'An explosive physical comedian whose all-in commitment made him one of the most beloved performers of the 1990s cast.',
    imageTone: 'from-red-950 via-orange-700 to-yellow-200',
    tags: ['Physical comedy', '90s cast', 'Chippendales'],
    highlights: ['Matt Foley', 'Chippendales audition', 'Tommy Boy'],
    catchphrases: ['Living in a van down by the river!'],
  },
  {
    id: 'david-spade',
    name: 'David Spade',
    type: 'alumni',
    years: '1990-1996',
    role: 'Cast member',
    bio: 'Dry, sardonic performer whose deadpan delivery paired perfectly with Chris Farley across SNL and a run of buddy comedies.',
    imageTone: 'from-zinc-950 via-sky-700 to-amber-200',
    tags: ['Deadpan', '90s cast', 'Buddy comedy'],
    highlights: ['Hollywood Minute', 'Tommy Boy', 'Just Shoot Me'],
    catchphrases: ['And you are?'],
  },
  {
    id: 'norm-macdonald',
    name: 'Norm Macdonald',
    type: 'alumni',
    years: '1993-1998',
    role: 'Cast member and Weekend Update anchor',
    bio: 'A cult-favorite Update anchor whose anti-comedy timing and Burt Reynolds impression made him a comedian’s comedian.',
    imageTone: 'from-stone-950 via-zinc-700 to-cyan-200',
    tags: ['Weekend Update', 'Deadpan', 'Anti-comedy'],
    highlights: ['Weekend Update', 'Burt Reynolds', 'Moth joke'],
  },
  {
    id: 'julia-louis-dreyfus',
    name: 'Julia Louis-Dreyfus',
    type: 'alumni',
    years: '1982-1985',
    role: 'Cast member',
    bio: 'One of the youngest cast members ever hired, she went on to become one of the most awarded comic actors in television history.',
    imageTone: 'from-purple-950 via-rose-700 to-amber-200',
    tags: ['80s cast', 'Sitcom legend', 'Emmy record'],
    highlights: ['Seinfeld', 'Veep', 'Elaine Benes'],
    awards: ['Emmy Awards', 'Mark Twain Prize'],
  },
  {
    id: 'billy-crystal',
    name: 'Billy Crystal',
    type: 'alumni',
    years: '1984-1985',
    role: 'Cast member',
    bio: 'A one-season cast member whose Fernando impression and warm showmanship launched a major film and hosting career.',
    imageTone: 'from-amber-950 via-orange-600 to-sky-200',
    tags: ['Impressions', '80s cast', 'Film comedy'],
    highlights: ['Fernando', 'When Harry Met Sally', 'Oscars host'],
    catchphrases: ['You look mahvelous.'],
  },
  {
    id: 'martin-short',
    name: 'Martin Short',
    type: 'alumni',
    years: '1984-1985',
    role: 'Cast member',
    bio: 'A manic character genius whose single explosive season produced some of SNL’s most committed character work.',
    imageTone: 'from-indigo-950 via-fuchsia-700 to-yellow-200',
    tags: ['Characters', '80s cast', 'Manic energy'],
    highlights: ['Ed Grimley', 'Three Amigos', 'Only Murders in the Building'],
    catchphrases: ['I must say.'],
  },
  {
    id: 'jon-lovitz',
    name: 'Jon Lovitz',
    type: 'alumni',
    years: '1985-1990',
    role: 'Cast member',
    bio: 'A reliable character man of the late-80s cast whose smug, theatrical creations defined an era of sketch personas.',
    imageTone: 'from-emerald-950 via-teal-700 to-orange-200',
    tags: ['Characters', '80s cast', 'Smug personas'],
    highlights: ['Master Thespian', 'Tommy Flanagan the liar', 'The Critic'],
    catchphrases: ['Yeah, that’s the ticket!'],
  },
  {
    id: 'will-forte',
    name: 'Will Forte',
    type: 'alumni',
    years: '2002-2010',
    role: 'Cast member and writer',
    bio: 'An absurdist writer-performer whose surreal characters became a feature franchise and a post-apocalyptic sitcom.',
    imageTone: 'from-neutral-950 via-lime-700 to-rose-200',
    tags: ['Absurdist', 'Characters', 'Writer-performer'],
    highlights: ['MacGruber', 'The Falconer', 'The Last Man on Earth'],
  },
  {
    id: 'jason-sudeikis',
    name: 'Jason Sudeikis',
    type: 'alumni',
    years: '2003-2013',
    role: 'Writer and cast member',
    bio: 'A versatile everyman performer whose SNL run preceded an Emmy-winning turn as one of television’s most beloved coaches.',
    imageTone: 'from-sky-950 via-blue-700 to-amber-200',
    tags: ['Everyman', '2000s cast', 'Writer-performer'],
    highlights: ['Devil sketches', 'Horrible Bosses', 'Ted Lasso'],
    awards: ['Emmy Awards', 'Golden Globe'],
  },
  {
    id: 'pete-davidson',
    name: 'Pete Davidson',
    type: 'alumni',
    years: '2014-2022',
    role: 'Cast member',
    bio: 'One of the youngest cast members of the 2010s, blending confessional stand-up with Weekend Update commentary and indie film.',
    imageTone: 'from-zinc-950 via-violet-700 to-cyan-200',
    tags: ['Stand-up', '2010s cast', 'Weekend Update'],
    highlights: ['Update commentary', 'The King of Staten Island', 'Chad'],
  },
  {
    id: 'cecily-strong',
    name: 'Cecily Strong',
    type: 'alumni',
    years: '2012-2022',
    role: 'Cast member and Weekend Update anchor',
    bio: 'A sharp impressionist and musical performer whose decade-long run bridged political satire and prestige musical comedy.',
    imageTone: 'from-rose-950 via-pink-600 to-teal-200',
    tags: ['Impressions', '2010s cast', 'Weekend Update'],
    highlights: ['The Girl You Wish You Hadn’t Started a Conversation With', 'Jeanine Pirro', 'Schmigadoon!'],
  },
  {
    id: 'aidy-bryant',
    name: 'Aidy Bryant',
    type: 'alumni',
    years: '2012-2022',
    role: 'Cast member',
    bio: 'A warm, fearless character performer of the 2010s ensemble who carried her sensibility into acclaimed half-hour comedy.',
    imageTone: 'from-amber-950 via-pink-700 to-emerald-200',
    tags: ['Characters', '2010s cast', 'Ensemble'],
    highlights: ['Update bits', 'Shrill', 'Girls5eva'],
  },
  {
    id: 'bowen-yang',
    name: 'Bowen Yang',
    type: 'alumni',
    years: '2019-present',
    role: 'Cast member and writer',
    bio: 'The first Chinese-American cast member, a breakout modern-era performer known for viral character turns and a hit podcast.',
    imageTone: 'from-fuchsia-950 via-purple-600 to-cyan-200',
    tags: ['Modern era', 'Characters', 'Writer-performer'],
    highlights: ['The iceberg that sank the Titanic', 'Las Culturistas', 'Wicked'],
    awards: ['Emmy nominations'],
  },
  {
    id: 'tracy-morgan',
    name: 'Tracy Morgan',
    type: 'alumni',
    years: '1996-2003',
    role: 'Cast member',
    bio: 'A wildly original sketch performer whose unpredictable energy reunited with Tina Fey for a defining sitcom role.',
    imageTone: 'from-indigo-950 via-amber-700 to-lime-200',
    tags: ['Characters', '90s-2000s cast', 'Ensemble'],
    highlights: ['Brian Fellow’s Safari Planet', 'Astronaut Jones', '30 Rock'],
  },
  {
    id: 'darrell-hammond',
    name: 'Darrell Hammond',
    type: 'alumni',
    years: '1995-2009',
    role: 'Cast member and announcer',
    bio: 'A master political impressionist who set the record for longest tenure as a cast member before becoming the show’s announcer.',
    imageTone: 'from-slate-950 via-zinc-600 to-amber-200',
    tags: ['Impressions', 'Political satire', 'Announcer'],
    highlights: ['Bill Clinton', 'Sean Connery', 'SNL announcer'],
  },
  {
    id: 'rachel-dratch',
    name: 'Rachel Dratch',
    type: 'alumni',
    years: '1999-2006',
    role: 'Cast member',
    bio: 'An improv-rooted character performer whose deadpan downer creation became a signature recurring sketch of the 2000s.',
    imageTone: 'from-zinc-950 via-emerald-700 to-rose-200',
    tags: ['Characters', '2000s cast', 'Improv'],
    highlights: ['Debbie Downer', 'Boston Teens', '30 Rock'],
  },
  {
    id: 'tim-robinson',
    name: 'Tim Robinson',
    type: 'alumni',
    years: '2012-2013',
    role: 'Cast member and writer',
    bio: 'A one-season cast member turned head writer whose absurdist sensibility became a cult sketch show and comedy touchstone.',
    imageTone: 'from-orange-950 via-red-700 to-cyan-200',
    tags: ['Absurdist', 'Writer', 'Cult comedy'],
    highlights: ['SNL writer', 'I Think You Should Leave', 'Detroiters'],
    catchphrases: ['You sure about that?'],
  },
  {
    id: 'bobby-moynihan',
    name: 'Bobby Moynihan',
    type: 'alumni',
    years: '2008-2017',
    role: 'Cast member',
    bio: 'A dependable character utility player of the 2010s whose recurring Weekend Update creation became a fan favorite.',
    imageTone: 'from-blue-950 via-indigo-700 to-amber-200',
    tags: ['Characters', '2010s cast', 'Weekend Update'],
    highlights: ['Drunk Uncle', 'Anthony Crispino', 'DuckTales'],
  },
  {
    id: 'kevin-nealon',
    name: 'Kevin Nealon',
    type: 'alumni',
    years: '1986-1995',
    role: 'Cast member and Weekend Update anchor',
    bio: 'A laid-back Update anchor and character performer whose bodybuilder duo became one of the late-80s cast’s defining bits.',
    imageTone: 'from-stone-950 via-yellow-700 to-sky-200',
    tags: ['Weekend Update', 'Characters', '90s cast'],
    highlights: ['Hans and Franz', 'Mr. Subliminal', 'Weeds'],
  },
  {
    id: 'colin-jost',
    name: 'Colin Jost',
    type: 'alumni',
    years: '2005-present',
    role: 'Head writer and Weekend Update anchor',
    bio: 'A longtime writer who became co-head writer and Update anchor, defining the desk’s modern era alongside Michael Che.',
    imageTone: 'from-sky-950 via-slate-700 to-amber-200',
    tags: ['Head writer', 'Weekend Update', 'Modern era'],
    highlights: ['Weekend Update', 'Joke Swap', 'Co-head writer'],
    awards: ['Emmy nominations'],
  },
  {
    id: 'michael-che',
    name: 'Michael Che',
    type: 'alumni',
    years: '2013-present',
    role: 'Head writer and Weekend Update anchor',
    bio: 'The first Black Weekend Update anchor and co-head writer, whose stand-up edge sharpened the desk’s modern voice.',
    imageTone: 'from-zinc-950 via-red-800 to-cyan-200',
    tags: ['Head writer', 'Weekend Update', 'Stand-up'],
    highlights: ['Weekend Update', 'Joke Swap', 'Co-head writer'],
    awards: ['Emmy nominations'],
  },

  // ── Creators & writers ──────────────────────────────────────────
  {
    id: 'lorne-michaels',
    name: 'Lorne Michaels',
    type: 'creator',
    years: '1975-present',
    role: 'Creator and producer',
    bio: 'The producer whose casting, writing rooms, and alumni pipeline make SNL feel like an expandable comedy universe.',
    imageTone: 'from-black via-zinc-700 to-red-300',
    tags: ['Producer', 'Talent pipeline', 'Broadway Video'],
    highlights: ['Created SNL', 'Produced 30 Rock', 'Launched generations'],
    awards: ['Emmy Awards', 'Kennedy Center Honors'],
  },
  {
    id: 'john-mulaney',
    name: 'John Mulaney',
    type: 'creator',
    years: '2008-2013',
    role: 'Writer turned host',
    bio: 'An SNL writer who co-created Stefon, then became a celebrated stand-up and a beloved recurring host of the show.',
    imageTone: 'from-indigo-950 via-blue-700 to-rose-200',
    tags: ['Writer', 'Stand-up', 'Recurring host'],
    highlights: ['Co-created Stefon', 'Diner Lobster', 'Five-Timers host club'],
    awards: ['Emmy Awards'],
  },
  {
    id: 'robert-smigel',
    name: 'Robert Smigel',
    type: 'creator',
    years: '1985-present',
    role: 'Writer and animator',
    bio: 'A longtime SNL writer behind TV Funhouse and Triumph the Insult Comic Dog, shaping the show’s animated and satirical edge.',
    imageTone: 'from-stone-950 via-amber-800 to-cyan-200',
    tags: ['Writer', 'Animation', 'TV Funhouse'],
    highlights: ['TV Funhouse', 'Triumph the Insult Comic Dog', 'Ambiguously Gay Duo'],
  },
  {
    id: 'conan-obrien',
    name: 'Conan O’Brien',
    type: 'creator',
    years: '1988-1991',
    role: 'Writer',
    bio: 'An SNL writer in the late 80s whose absurdist instincts carried into a generation-defining late-night career.',
    imageTone: 'from-orange-950 via-red-700 to-sky-200',
    tags: ['Writer', 'Late night', 'Absurdist'],
    highlights: ['SNL writer', 'Late Night with Conan O’Brien', 'Conan'],
    awards: ['Emmy Awards', 'Mark Twain Prize'],
  },
  {
    id: 'harold-ramis',
    name: 'Harold Ramis',
    type: 'creator',
    years: '1980s-2000s',
    role: 'Writer and director',
    bio: 'A pivotal comedy writer-director who never joined SNL but co-built the films that turned its early stars into icons.',
    imageTone: 'from-zinc-950 via-emerald-800 to-amber-200',
    tags: ['Director', 'Co-writer', 'Film bridge'],
    highlights: ['Ghostbusters', 'Caddyshack', 'Groundhog Day'],
  },

  // ── Movies ──────────────────────────────────────────────────────
  {
    id: 'ghostbusters',
    name: 'Ghostbusters',
    type: 'movie',
    years: '1984',
    role: 'Supernatural comedy film',
    bio: 'A major bridge from early SNL talent into blockbuster genre comedy.',
    imageTone: 'from-gray-950 via-emerald-700 to-white',
    tags: ['Film', 'Supernatural comedy', 'Franchise'],
    highlights: ['Bill Murray', 'Dan Aykroyd', 'Harold Ramis'],
  },
  {
    id: 'mean-girls',
    name: 'Mean Girls',
    type: 'movie',
    years: '2004',
    role: 'Teen comedy film',
    bio: 'A Tina Fey-written comedy that extended SNL writing instincts into a quotable film and stage universe.',
    imageTone: 'from-pink-950 via-rose-500 to-white',
    tags: ['Film', 'Written by Tina Fey', 'Pop culture'],
    highlights: ['Tina Fey screenplay', 'Lorne Michaels production', 'Broadway adaptation'],
  },
  {
    id: 'caddyshack',
    name: 'Caddyshack',
    type: 'movie',
    years: '1980',
    role: 'Sports comedy film',
    bio: 'A classic comedy connecting original SNL-era performers with Harold Ramis and early studio comedy mythology.',
    imageTone: 'from-green-950 via-lime-700 to-yellow-200',
    tags: ['Film', 'Sports comedy', '1980s comedy'],
    highlights: ['Chevy Chase', 'Bill Murray', 'Harold Ramis'],
  },
  {
    id: 'blues-brothers',
    name: 'The Blues Brothers',
    type: 'movie',
    years: '1980',
    role: 'Musical comedy film',
    bio: 'A film expansion of an SNL music-comedy act built around John Belushi and Dan Aykroyd.',
    imageTone: 'from-black via-blue-900 to-white',
    tags: ['Film', 'Music comedy', 'SNL spin-off'],
    highlights: ['John Belushi', 'Dan Aykroyd', 'Sketch-to-film'],
  },
  {
    id: 'waynes-world',
    name: 'Wayne’s World',
    type: 'movie',
    years: '1992',
    role: 'Sketch-based comedy film',
    bio: 'A breakout SNL sketch-to-film success centered on basement public-access hosts Wayne and Garth.',
    imageTone: 'from-slate-950 via-blue-700 to-orange-200',
    tags: ['Film', 'Sketch-to-film', '1990s comedy'],
    highlights: ['Mike Myers', 'Dana Carvey', 'Party on'],
  },
  {
    id: 'austin-powers',
    name: 'Austin Powers',
    type: 'movie',
    years: '1997',
    role: 'Spy comedy film',
    bio: 'A Mike Myers-led franchise that extended his character-comedy instincts beyond SNL into global pop culture.',
    imageTone: 'from-purple-950 via-fuchsia-700 to-yellow-200',
    tags: ['Film', 'Franchise', 'Character comedy'],
    highlights: ['Mike Myers', 'Spy parody', 'Multiple roles'],
  },
  {
    id: 'shrek',
    name: 'Shrek',
    type: 'movie',
    years: '2001',
    role: 'Animated comedy film',
    bio: 'A landmark animated franchise voiced by Mike Myers and Eddie Murphy, uniting two SNL eras in one blockbuster.',
    imageTone: 'from-green-950 via-lime-600 to-amber-200',
    tags: ['Film', 'Animation', 'Franchise'],
    highlights: ['Mike Myers', 'Eddie Murphy', 'Best Animated Feature Oscar'],
  },
  {
    id: 'superstar',
    name: 'Superstar',
    type: 'movie',
    years: '1999',
    role: 'Sketch-based comedy film',
    bio: 'Mary Katherine Gallagher moved from recurring SNL character to feature comedy.',
    imageTone: 'from-red-950 via-orange-500 to-white',
    tags: ['Film', 'Sketch-to-film', 'Character comedy'],
    highlights: ['Molly Shannon', 'Mary Katherine Gallagher', 'SNL spin-off'],
  },
  {
    id: 'bridesmaids',
    name: 'Bridesmaids',
    type: 'movie',
    years: '2011',
    role: 'Ensemble comedy film',
    bio: 'A major modern comedy ensemble connecting Kristen Wiig, Maya Rudolph, and the post-2000 SNL era.',
    imageTone: 'from-fuchsia-950 via-pink-600 to-yellow-200',
    tags: ['Film', 'Ensemble', 'Written by Kristen Wiig'],
    highlights: ['Kristen Wiig', 'Maya Rudolph', 'Oscar nominations'],
  },
  {
    id: 'groundhog-day',
    name: 'Groundhog Day',
    type: 'movie',
    years: '1993',
    role: 'Fantasy comedy film',
    bio: 'A beloved time-loop comedy that paired Bill Murray with director Harold Ramis at the peak of their collaboration.',
    imageTone: 'from-sky-950 via-indigo-700 to-amber-200',
    tags: ['Film', 'Time loop', '1990s classic'],
    highlights: ['Bill Murray', 'Harold Ramis', 'Time-loop classic'],
  },
  {
    id: 'stripes',
    name: 'Stripes',
    type: 'movie',
    years: '1981',
    role: 'Military comedy film',
    bio: 'An early-80s service comedy that teamed Bill Murray with Harold Ramis and helped cement the SNL-to-studio pipeline.',
    imageTone: 'from-stone-950 via-green-800 to-amber-200',
    tags: ['Film', 'Military comedy', '1980s comedy'],
    highlights: ['Bill Murray', 'Harold Ramis', 'Army hijinks'],
  },
  {
    id: 'coming-to-america',
    name: 'Coming to America',
    type: 'movie',
    years: '1988',
    role: 'Romantic comedy film',
    bio: 'A showcase for Eddie Murphy’s multi-character range that became one of the defining comedies of the late 1980s.',
    imageTone: 'from-purple-950 via-amber-700 to-rose-200',
    tags: ['Film', 'Multiple roles', '1980s comedy'],
    highlights: ['Eddie Murphy', 'Multiple characters', 'Cult sequel'],
  },
  {
    id: 'trading-places',
    name: 'Trading Places',
    type: 'movie',
    years: '1983',
    role: 'Comedy film',
    bio: 'A social-satire comedy pairing Eddie Murphy and Dan Aykroyd, linking two SNL generations on screen.',
    imageTone: 'from-emerald-950 via-amber-700 to-sky-200',
    tags: ['Film', 'Satire', '1980s comedy'],
    highlights: ['Eddie Murphy', 'Dan Aykroyd', 'Wall Street satire'],
  },
  {
    id: 'beverly-hills-cop',
    name: 'Beverly Hills Cop',
    type: 'movie',
    years: '1984',
    role: 'Action comedy film',
    bio: 'The blockbuster that confirmed Eddie Murphy as a global movie star straight out of his SNL run.',
    imageTone: 'from-zinc-950 via-red-700 to-cyan-200',
    tags: ['Film', 'Action comedy', 'Franchise'],
    highlights: ['Eddie Murphy', 'Axel Foley', 'Box-office franchise'],
  },
  {
    id: 'tommy-boy',
    name: 'Tommy Boy',
    type: 'movie',
    years: '1995',
    role: 'Buddy comedy film',
    bio: 'The definitive Chris Farley and David Spade buddy comedy, born directly from their SNL chemistry.',
    imageTone: 'from-red-950 via-orange-700 to-sky-200',
    tags: ['Film', 'Buddy comedy', 'SNL pairing'],
    highlights: ['Chris Farley', 'David Spade', 'Road-trip comedy'],
  },
  {
    id: 'billy-madison',
    name: 'Billy Madison',
    type: 'movie',
    years: '1995',
    role: 'Comedy film',
    bio: 'Adam Sandler’s first leading vehicle, launching the loud, absurd persona he built at SNL into a film career.',
    imageTone: 'from-blue-950 via-violet-700 to-amber-200',
    tags: ['Film', 'Sandler vehicle', '1990s comedy'],
    highlights: ['Adam Sandler', 'Back to school', 'Cult quotability'],
  },
  {
    id: 'happy-gilmore',
    name: 'Happy Gilmore',
    type: 'movie',
    years: '1996',
    role: 'Sports comedy film',
    bio: 'Adam Sandler’s breakout sports comedy and one of the cornerstones of his enduring film franchise era.',
    imageTone: 'from-green-950 via-emerald-700 to-yellow-200',
    tags: ['Film', 'Sports comedy', 'Sandler vehicle'],
    highlights: ['Adam Sandler', 'The price is wrong', 'Netflix sequel'],
  },
  {
    id: 'grown-ups',
    name: 'Grown Ups',
    type: 'movie',
    years: '2010',
    role: 'Ensemble comedy film',
    bio: 'An SNL-alumni reunion comedy gathering Adam Sandler, Chris Rock, David Spade, and the Sandler comedy ecosystem.',
    imageTone: 'from-sky-950 via-blue-700 to-lime-200',
    tags: ['Film', 'Ensemble', 'SNL reunion'],
    highlights: ['Adam Sandler', 'Chris Rock', 'David Spade'],
  },
  {
    id: 'anchorman',
    name: 'Anchorman',
    type: 'movie',
    years: '2004',
    role: 'Comedy film',
    bio: 'The quotable Will Ferrell ensemble comedy that defined the mid-2000s studio comedy boom he led after SNL.',
    imageTone: 'from-amber-950 via-orange-600 to-sky-200',
    tags: ['Film', 'Ensemble', 'Quotable'],
    highlights: ['Will Ferrell', 'Ron Burgundy', 'Stay classy'],
  },
  {
    id: 'talladega-nights',
    name: 'Talladega Nights',
    type: 'movie',
    years: '2006',
    role: 'Sports comedy film',
    bio: 'A NASCAR satire built around Will Ferrell’s big-swing comic persona at the height of his box-office run.',
    imageTone: 'from-red-950 via-yellow-700 to-cyan-200',
    tags: ['Film', 'Sports comedy', 'Ferrell vehicle'],
    highlights: ['Will Ferrell', 'Ricky Bobby', 'Shake and bake'],
  },
  {
    id: 'step-brothers',
    name: 'Step Brothers',
    type: 'movie',
    years: '2008',
    role: 'Comedy film',
    bio: 'A cult Will Ferrell man-child comedy that became one of the most endlessly quoted films of his post-SNL era.',
    imageTone: 'from-indigo-950 via-blue-700 to-amber-200',
    tags: ['Film', 'Cult comedy', 'Ferrell vehicle'],
    highlights: ['Will Ferrell', 'Prestige Worldwide', 'Quotable'],
  },
  {
    id: 'elf',
    name: 'Elf',
    type: 'movie',
    years: '2003',
    role: 'Holiday comedy film',
    bio: 'A modern Christmas classic that showcased Will Ferrell’s wide-eyed sincerity for a family audience.',
    imageTone: 'from-green-950 via-red-700 to-white',
    tags: ['Film', 'Holiday classic', 'Ferrell vehicle'],
    highlights: ['Will Ferrell', 'Buddy the Elf', 'Christmas staple'],
  },
  {
    id: 'macgruber-movie',
    name: 'MacGruber',
    type: 'movie',
    years: '2010',
    role: 'Action comedy film',
    bio: 'A feature-length expansion of Will Forte’s MacGyver-parody sketch into a cult action-comedy and later a series.',
    imageTone: 'from-stone-950 via-lime-700 to-red-200',
    tags: ['Film', 'Sketch-to-film', 'Cult comedy'],
    highlights: ['Will Forte', 'Kristen Wiig', 'Sketch-to-film'],
  },
  {
    id: 'coneheads-movie',
    name: 'Coneheads',
    type: 'movie',
    years: '1993',
    role: 'Sci-fi comedy film',
    bio: 'A feature adaptation of the classic SNL alien-family sketch, reuniting Dan Aykroyd with the original concept.',
    imageTone: 'from-zinc-950 via-indigo-700 to-lime-200',
    tags: ['Film', 'Sketch-to-film', 'Sci-fi comedy'],
    highlights: ['Dan Aykroyd', 'The Coneheads', 'Sketch-to-film'],
  },
  {
    id: 'three-amigos',
    name: 'Three Amigos',
    type: 'movie',
    years: '1986',
    role: 'Western comedy film',
    bio: 'A western-parody team-up that united SNL alums Chevy Chase and Martin Short with Steve Martin.',
    imageTone: 'from-amber-950 via-orange-700 to-sky-200',
    tags: ['Film', 'Western comedy', 'Ensemble'],
    highlights: ['Chevy Chase', 'Martin Short', 'Steve Martin'],
  },
  {
    id: 'when-harry-met-sally',
    name: 'When Harry Met Sally',
    type: 'movie',
    years: '1989',
    role: 'Romantic comedy film',
    bio: 'The genre-defining rom-com that turned SNL alum Billy Crystal into a leading-man fixture.',
    imageTone: 'from-rose-950 via-amber-600 to-sky-200',
    tags: ['Film', 'Romantic comedy', 'Classic'],
    highlights: ['Billy Crystal', 'I’ll have what she’s having', 'Rom-com landmark'],
  },
  {
    id: 'baby-mama',
    name: 'Baby Mama',
    type: 'movie',
    years: '2008',
    role: 'Comedy film',
    bio: 'A buddy comedy reuniting Weekend Update partners Tina Fey and Amy Poehler as on-screen leads.',
    imageTone: 'from-teal-950 via-rose-600 to-amber-200',
    tags: ['Film', 'Buddy comedy', 'Fey & Poehler'],
    highlights: ['Tina Fey', 'Amy Poehler', 'Update reunion'],
  },
  {
    id: 'sisters',
    name: 'Sisters',
    type: 'movie',
    years: '2015',
    role: 'Comedy film',
    bio: 'A raucous Tina Fey and Amy Poehler comedy that doubled down on their decades-long comedic partnership.',
    imageTone: 'from-pink-950 via-purple-600 to-cyan-200',
    tags: ['Film', 'Buddy comedy', 'Fey & Poehler'],
    highlights: ['Tina Fey', 'Amy Poehler', 'House-party comedy'],
  },
  {
    id: 'popstar',
    name: 'Popstar: Never Stop Never Stopping',
    type: 'movie',
    years: '2016',
    role: 'Mockumentary film',
    bio: 'The Lonely Island’s music-industry mockumentary, extending Andy Samberg’s SNL digital-short DNA into a feature.',
    imageTone: 'from-fuchsia-950 via-blue-700 to-yellow-200',
    tags: ['Film', 'Mockumentary', 'Lonely Island'],
    highlights: ['Andy Samberg', 'The Lonely Island', 'Music comedy'],
  },
  {
    id: 'hot-rod',
    name: 'Hot Rod',
    type: 'movie',
    years: '2007',
    role: 'Comedy film',
    bio: 'A cult Lonely Island comedy starring Andy Samberg, beloved for its absurdist tone and quotable energy.',
    imageTone: 'from-orange-950 via-red-700 to-amber-200',
    tags: ['Film', 'Cult comedy', 'Lonely Island'],
    highlights: ['Andy Samberg', 'Cool beans', 'Stunt comedy'],
  },
  {
    id: 'king-of-staten-island',
    name: 'The King of Staten Island',
    type: 'movie',
    years: '2020',
    role: 'Comedy-drama film',
    bio: 'A semi-autobiographical Pete Davidson film that translated his confessional comic voice into a feature drama.',
    imageTone: 'from-zinc-950 via-violet-700 to-amber-200',
    tags: ['Film', 'Comedy-drama', 'Davidson vehicle'],
    highlights: ['Pete Davidson', 'Judd Apatow', 'Semi-autobiographical'],
  },
  {
    id: 'animal-house',
    name: 'Animal House',
    type: 'movie',
    years: '1978',
    role: 'Comedy film',
    bio: 'The frat-comedy blueprint that made John Belushi a movie star while SNL was still in its first seasons.',
    imageTone: 'from-stone-950 via-amber-800 to-sky-200',
    tags: ['Film', 'Frat comedy', '1970s landmark'],
    highlights: ['John Belushi', 'Bluto', 'Comedy blueprint'],
  },

  // ── TV shows ────────────────────────────────────────────────────
  {
    id: 'thirty-rock',
    name: '30 Rock',
    type: 'tv',
    years: '2006-2013',
    role: 'Network sitcom',
    bio: 'A backstage comedy that channels SNL production culture into a rapid-fire sitcom.',
    imageTone: 'from-slate-950 via-teal-700 to-amber-200',
    tags: ['TV', 'Workplace comedy', 'NBC'],
    highlights: ['Tina Fey', 'Tracy Morgan', 'Emmy-winning sitcom'],
  },
  {
    id: 'parks-rec',
    name: 'Parks and Recreation',
    type: 'tv',
    years: '2009-2015',
    role: 'Workplace sitcom',
    bio: 'An Amy Poehler-led ensemble comedy connected to SNL through performers, writers, and improv culture.',
    imageTone: 'from-green-950 via-lime-700 to-yellow-200',
    tags: ['TV', 'Ensemble', 'Workplace comedy'],
    highlights: ['Amy Poehler', 'Nick Offerman', 'Optimistic civic comedy'],
  },
  {
    id: 'portlandia',
    name: 'Portlandia',
    type: 'tv',
    years: '2011-2018',
    role: 'Sketch comedy series',
    bio: 'Fred Armisen and Carrie Brownstein built a stylized sketch universe around Pacific Northwest culture.',
    imageTone: 'from-emerald-950 via-green-700 to-pink-200',
    tags: ['TV', 'Sketch comedy', 'Alternative comedy'],
    highlights: ['Fred Armisen', 'Carrie Brownstein', 'Peabody-winning satire'],
  },
  {
    id: 'brooklyn-nine-nine',
    name: 'Brooklyn Nine-Nine',
    type: 'tv',
    years: '2013-2021',
    role: 'Workplace sitcom',
    bio: 'An ensemble cop comedy that carried Andy Samberg’s SNL rhythm into a beloved long-running network sitcom.',
    imageTone: 'from-blue-950 via-cyan-700 to-amber-200',
    tags: ['TV', 'Ensemble', 'Workplace comedy'],
    highlights: ['Andy Samberg', 'Jake Peralta', 'Cult network sitcom'],
  },
  {
    id: 'documentary-now',
    name: 'Documentary Now!',
    type: 'tv',
    years: '2015-present',
    role: 'Mockumentary series',
    bio: 'A meticulous documentary-parody series co-created by SNL alums Fred Armisen, Bill Hader, and Seth Meyers.',
    imageTone: 'from-stone-950 via-emerald-700 to-rose-200',
    tags: ['TV', 'Mockumentary', 'Alternative comedy'],
    highlights: ['Fred Armisen', 'Bill Hader', 'Seth Meyers'],
  },
  {
    id: 'tonight-show',
    name: 'The Tonight Show',
    type: 'tv',
    years: '2014-present',
    role: 'Late-night talk show',
    bio: 'The flagship late-night franchise that Jimmy Fallon took over, carrying his SNL musical-comedy energy to the desk.',
    imageTone: 'from-sky-950 via-blue-700 to-white',
    tags: ['TV', 'Late night', 'Talk show'],
    highlights: ['Jimmy Fallon', 'Viral games', 'Late-night flagship'],
  },
  {
    id: 'late-night-seth',
    name: 'Late Night with Seth Meyers',
    type: 'tv',
    years: '2014-present',
    role: 'Late-night talk show',
    bio: 'Seth Meyers’ late-night home, where his Weekend Update voice evolved into sharp political segments like A Closer Look.',
    imageTone: 'from-indigo-950 via-slate-700 to-cyan-200',
    tags: ['TV', 'Late night', 'Political comedy'],
    highlights: ['Seth Meyers', 'A Closer Look', 'Update lineage'],
  },
  {
    id: 'kenan-show',
    name: 'Kenan',
    type: 'tv',
    years: '2021-2022',
    role: 'Sitcom',
    bio: 'A network sitcom built around Kenan Thompson while he simultaneously remained an active SNL cast member.',
    imageTone: 'from-amber-950 via-yellow-700 to-cyan-200',
    tags: ['TV', 'Sitcom', 'NBC'],
    highlights: ['Kenan Thompson', 'Family sitcom', 'Concurrent with SNL'],
  },
  {
    id: 'barry',
    name: 'Barry',
    type: 'tv',
    years: '2018-2023',
    role: 'Prestige comedy-drama',
    bio: 'Bill Hader’s acclaimed hitman-turned-actor series, a prestige showcase for his post-SNL writing and directing.',
    imageTone: 'from-violet-950 via-purple-700 to-lime-200',
    tags: ['TV', 'Prestige', 'Comedy-drama'],
    highlights: ['Bill Hader', 'Hitman turned actor', 'Emmy-winning'],
  },
  {
    id: 'big-mouth',
    name: 'Big Mouth',
    type: 'tv',
    years: '2017-present',
    role: 'Animated comedy series',
    bio: 'An adult animated comedy where Maya Rudolph’s voice work as the Hormone Monstress became a fan favorite.',
    imageTone: 'from-zinc-950 via-pink-700 to-green-200',
    tags: ['TV', 'Animation', 'Voice acting'],
    highlights: ['Maya Rudolph', 'Hormone Monstress', 'Voice comedy'],
  },
  {
    id: 'seinfeld',
    name: 'Seinfeld',
    type: 'tv',
    years: '1989-1998',
    role: 'Sitcom',
    bio: 'The landmark sitcom where SNL alum Julia Louis-Dreyfus created one of TV’s most iconic comic characters.',
    imageTone: 'from-blue-950 via-sky-700 to-amber-200',
    tags: ['TV', 'Sitcom', '1990s landmark'],
    highlights: ['Julia Louis-Dreyfus', 'Elaine Benes', 'Show about nothing'],
  },
  {
    id: 'veep',
    name: 'Veep',
    type: 'tv',
    years: '2012-2019',
    role: 'Political satire series',
    bio: 'A savage political comedy that earned Julia Louis-Dreyfus a record-setting run of lead-actress Emmys.',
    imageTone: 'from-purple-950 via-rose-700 to-cyan-200',
    tags: ['TV', 'Political satire', 'Prestige comedy'],
    highlights: ['Julia Louis-Dreyfus', 'Selina Meyer', 'Emmy record'],
  },
  {
    id: 'ted-lasso',
    name: 'Ted Lasso',
    type: 'tv',
    years: '2020-2023',
    role: 'Comedy-drama series',
    bio: 'The breakout feel-good series co-created by and starring SNL alum Jason Sudeikis as an optimistic American coach.',
    imageTone: 'from-sky-950 via-blue-700 to-amber-200',
    tags: ['TV', 'Comedy-drama', 'Feel-good'],
    highlights: ['Jason Sudeikis', 'Believe', 'Emmy-winning'],
  },
  {
    id: 'i-think-you-should-leave',
    name: 'I Think You Should Leave',
    type: 'tv',
    years: '2019-present',
    role: 'Sketch comedy series',
    bio: 'Tim Robinson’s cult sketch series that turned his SNL-honed absurdism into a defining modern comedy phenomenon.',
    imageTone: 'from-orange-950 via-red-700 to-cyan-200',
    tags: ['TV', 'Sketch comedy', 'Cult comedy'],
    highlights: ['Tim Robinson', 'Hot dog suit', 'Meme machine'],
  },
  {
    id: 'newsradio',
    name: 'NewsRadio',
    type: 'tv',
    years: '1995-1999',
    role: 'Workplace sitcom',
    bio: 'A sharp ensemble workplace sitcom where Phil Hartman delivered one of his most beloved post-SNL roles.',
    imageTone: 'from-slate-950 via-blue-800 to-amber-200',
    tags: ['TV', 'Workplace comedy', '1990s'],
    highlights: ['Phil Hartman', 'Bill McNeal', 'Ensemble sitcom'],
  },
  {
    id: 'last-man-earth',
    name: 'The Last Man on Earth',
    type: 'tv',
    years: '2015-2018',
    role: 'Post-apocalyptic sitcom',
    bio: 'Will Forte’s inventive end-of-the-world sitcom, a high-concept extension of his absurdist SNL voice.',
    imageTone: 'from-neutral-950 via-lime-700 to-rose-200',
    tags: ['TV', 'High-concept', 'Sitcom'],
    highlights: ['Will Forte', 'Phil Miller', 'End-of-the-world comedy'],
  },
  {
    id: 'schmigadoon',
    name: 'Schmigadoon!',
    type: 'tv',
    years: '2021-2023',
    role: 'Musical comedy series',
    bio: 'A musical-theater parody series starring Cecily Strong that leaned into her SNL musical-comedy strengths.',
    imageTone: 'from-rose-950 via-pink-600 to-teal-200',
    tags: ['TV', 'Musical comedy', 'Parody'],
    highlights: ['Cecily Strong', 'Musical parody', 'Apple TV+'],
  },

  // ── Characters & recurring sketches ─────────────────────────────
  {
    id: 'stefon',
    name: 'Stefon',
    type: 'character',
    years: '2008-2013',
    role: 'Weekend Update character',
    bio: 'Bill Hader and John Mulaney created a nightlife correspondent who became one of SNL’s defining Update characters.',
    imageTone: 'from-violet-950 via-fuchsia-600 to-lime-200',
    tags: ['Character', 'Weekend Update', 'Nightlife'],
    highlights: ['Performed by Bill Hader', 'Written with John Mulaney', 'Recurring Update favorite'],
    catchphrases: ['This place has everything.'],
  },
  {
    id: 'wayne-campbell',
    name: 'Wayne Campbell',
    type: 'character',
    years: '1989-1994',
    role: 'Recurring sketch character',
    bio: 'Mike Myers’ public-access metalhead host became one of SNL’s most successful sketch-to-film characters.',
    imageTone: 'from-zinc-950 via-blue-700 to-amber-200',
    tags: ['Character', 'Wayne’s World', 'Sketch-to-film'],
    highlights: ['Performed by Mike Myers', 'Wayne’s World', 'Party on'],
    catchphrases: ['Party on.'],
  },
  {
    id: 'church-lady',
    name: 'The Church Lady',
    type: 'character',
    years: '1986-1990s',
    role: 'Recurring sketch character',
    bio: 'Dana Carvey’s judgmental Church Chat host became a signature SNL character of the late 1980s.',
    imageTone: 'from-indigo-950 via-blue-700 to-white',
    tags: ['Character', 'Dana Carvey', 'Church Chat'],
    highlights: ['Performed by Dana Carvey', 'Church Chat', 'Recurring character'],
    catchphrases: ['Well, isn’t that special?'],
  },
  {
    id: 'mary-katherine-gallagher',
    name: 'Mary Katherine Gallagher',
    type: 'character',
    years: '1995-2001',
    role: 'Recurring sketch character',
    bio: 'Molly Shannon’s hyper-intense Catholic schoolgirl became a breakout character of the 1995 cast.',
    imageTone: 'from-rose-950 via-red-600 to-white',
    tags: ['Character', 'Molly Shannon', 'Physical comedy'],
    highlights: ['Performed by Molly Shannon', 'Superstar', '90s breakout character'],
  },
  {
    id: 'gumby',
    name: 'Gumby',
    type: 'character',
    years: '1980s',
    role: 'Recurring sketch character',
    bio: 'Eddie Murphy’s cigar-chomping show-business version of Gumby became one of his signature SNL characters.',
    imageTone: 'from-green-950 via-lime-600 to-yellow-200',
    tags: ['Character', 'Eddie Murphy', 'Recurring sketch'],
    highlights: ['Performed by Eddie Murphy', '1980s SNL', 'Character comedy'],
    catchphrases: ['I am Gumby, dammit.'],
  },
  {
    id: 'what-up-with-that',
    name: 'What Up With That',
    type: 'character',
    years: '2009-2010s',
    role: 'Recurring sketch format',
    bio: 'Kenan Thompson’s exuberant talk-show host Diondre Cole repeatedly derails celebrity interviews with song and dance.',
    imageTone: 'from-orange-950 via-yellow-600 to-cyan-200',
    tags: ['Sketch', 'Kenan Thompson', 'Music comedy'],
    highlights: ['Performed by Kenan Thompson', 'Recurring talk-show sketch', 'Musical chaos'],
  },
  {
    id: 'matt-foley',
    name: 'Matt Foley',
    type: 'character',
    years: '1993-1995',
    role: 'Recurring sketch character',
    bio: 'Chris Farley’s explosive motivational speaker is one of the most physically committed characters in SNL history.',
    imageTone: 'from-red-950 via-orange-700 to-amber-200',
    tags: ['Character', 'Chris Farley', 'Physical comedy'],
    highlights: ['Performed by Chris Farley', 'Motivational speaker', 'Van down by the river'],
    catchphrases: ['Living in a van down by the river!'],
  },
  {
    id: 'debbie-downer',
    name: 'Debbie Downer',
    type: 'character',
    years: '2004-2006',
    role: 'Recurring sketch character',
    bio: 'Rachel Dratch’s relentlessly negative party guest became a 2000s catchphrase and a famous break-prone sketch.',
    imageTone: 'from-zinc-950 via-emerald-700 to-rose-200',
    tags: ['Character', 'Rachel Dratch', '2000s sketch'],
    highlights: ['Performed by Rachel Dratch', 'Famous breaking sketch', 'Catchphrase coinage'],
    catchphrases: ['Wah-wah.'],
  },
  {
    id: 'macgruber',
    name: 'MacGruber',
    type: 'character',
    years: '2007-2010',
    role: 'Recurring sketch character',
    bio: 'Will Forte’s incompetent MacGyver parody who always blows up the bomb, spun off into a feature film and series.',
    imageTone: 'from-stone-950 via-lime-700 to-red-200',
    tags: ['Character', 'Will Forte', 'Sketch-to-film'],
    highlights: ['Performed by Will Forte', 'MacGyver parody', 'Sketch-to-film'],
  },
  {
    id: 'ed-grimley',
    name: 'Ed Grimley',
    type: 'character',
    years: '1984-1985',
    role: 'Recurring sketch character',
    bio: 'Martin Short’s twitchy, triangle-haired man-child became one of the most distinctive characters of the 80s cast.',
    imageTone: 'from-indigo-950 via-fuchsia-700 to-yellow-200',
    tags: ['Character', 'Martin Short', '80s sketch'],
    highlights: ['Performed by Martin Short', 'Triangle hair', 'I must say'],
    catchphrases: ['I must say.'],
  },
  {
    id: 'unfrozen-caveman-lawyer',
    name: 'Unfrozen Caveman Lawyer',
    type: 'character',
    years: '1991-1996',
    role: 'Recurring sketch character',
    bio: 'Phil Hartman’s prehistoric attorney who pleads ignorance of the modern world while delivering devastating closing arguments.',
    imageTone: 'from-slate-950 via-amber-800 to-sky-200',
    tags: ['Character', 'Phil Hartman', '90s sketch'],
    highlights: ['Performed by Phil Hartman', 'Courtroom satire', 'Your world frightens and confuses me'],
    catchphrases: ['I’m just a caveman.'],
  },
  {
    id: 'roseanne-roseannadanna',
    name: 'Roseanne Roseannadanna',
    type: 'character',
    years: '1978-1980',
    role: 'Weekend Update character',
    bio: 'Gilda Radner’s gloriously gross Update correspondent whose tangents became an original-era SNL hallmark.',
    imageTone: 'from-rose-950 via-pink-600 to-amber-200',
    tags: ['Character', 'Gilda Radner', 'Weekend Update'],
    highlights: ['Performed by Gilda Radner', 'Weekend Update', 'It’s always something'],
    catchphrases: ['It’s always something.'],
  },
  {
    id: 'mr-robinson',
    name: 'Mister Robinson’s Neighborhood',
    type: 'character',
    years: '1981-1985',
    role: 'Recurring sketch character',
    bio: 'Eddie Murphy’s street-wise parody of Mister Rogers, one of the sharpest satirical creations of his SNL run.',
    imageTone: 'from-purple-950 via-fuchsia-700 to-yellow-200',
    tags: ['Character', 'Eddie Murphy', 'Parody'],
    highlights: ['Performed by Eddie Murphy', 'Mister Rogers parody', 'Recurring sketch'],
  },
  {
    id: 'hans-and-franz',
    name: 'Hans and Franz',
    type: 'character',
    years: '1987-1991',
    role: 'Recurring sketch duo',
    bio: 'Dana Carvey and Kevin Nealon’s Austrian bodybuilders who wanted to pump you up became a late-80s staple.',
    imageTone: 'from-stone-950 via-yellow-700 to-sky-200',
    tags: ['Character', 'Carvey & Nealon', '80s sketch'],
    highlights: ['Dana Carvey', 'Kevin Nealon', 'Pump you up'],
    catchphrases: ['We’re here to pump you up!'],
  },
  {
    id: 'target-lady',
    name: 'Target Lady',
    type: 'character',
    years: '2005-2012',
    role: 'Recurring sketch character',
    bio: 'Kristen Wiig’s overenthusiastic Target cashier, a showcase for her specific, committed character comedy.',
    imageTone: 'from-red-950 via-rose-600 to-white',
    tags: ['Character', 'Kristen Wiig', '2000s sketch'],
    highlights: ['Performed by Kristen Wiig', 'Retail satire', 'Recurring sketch'],
  },
  {
    id: 'drunk-uncle',
    name: 'Drunk Uncle',
    type: 'character',
    years: '2011-2017',
    role: 'Weekend Update character',
    bio: 'Bobby Moynihan’s maudlin, reactionary holiday relative who slurs his way through Weekend Update segments.',
    imageTone: 'from-blue-950 via-indigo-700 to-amber-200',
    tags: ['Character', 'Bobby Moynihan', 'Weekend Update'],
    highlights: ['Performed by Bobby Moynihan', 'Weekend Update', 'Holiday staple'],
  },
  {
    id: 'the-girl-you-wish',
    name: 'The Girl You Wish You Hadn’t Started a Conversation With',
    type: 'character',
    years: '2013-2016',
    role: 'Weekend Update character',
    bio: 'Cecily Strong’s overconfident party guest who confidently misstates everything, a standout 2010s Update character.',
    imageTone: 'from-rose-950 via-pink-600 to-teal-200',
    tags: ['Character', 'Cecily Strong', 'Weekend Update'],
    highlights: ['Performed by Cecily Strong', 'Weekend Update', 'Confident misinformation'],
  },

  // ── Awards ──────────────────────────────────────────────────────
  {
    id: 'emmy-award',
    name: 'Emmy Award',
    type: 'award',
    role: 'Television academy award',
    bio: 'Television’s highest honor, won repeatedly across generations of SNL alumni for performing, writing, and producing.',
    imageTone: 'from-yellow-900 via-amber-600 to-white',
    tags: ['Award', 'Television', 'Prestige'],
    highlights: ['Tina Fey', 'Bill Hader', 'Kate McKinnon'],
  },
  {
    id: 'mark-twain-prize',
    name: 'Mark Twain Prize',
    type: 'award',
    role: 'American humor honor',
    bio: 'The Kennedy Center’s lifetime honor for American humor, awarded to several SNL alumni and Lorne Michaels.',
    imageTone: 'from-amber-900 via-orange-600 to-rose-200',
    tags: ['Award', 'Lifetime honor', 'Comedy'],
    highlights: ['Tina Fey', 'Eddie Murphy', 'Will Ferrell'],
  },
  {
    id: 'academy-award',
    name: 'Academy Award',
    type: 'award',
    role: 'Film academy award',
    bio: 'Film’s top honor, reached by SNL alumni through screenwriting, animation, and acclaimed dramatic and comedic roles.',
    imageTone: 'from-yellow-900 via-yellow-600 to-white',
    tags: ['Award', 'Film', 'Prestige'],
    highlights: ['Shrek (Best Animated Feature)', 'Kristen Wiig nomination', 'Film recognition'],
  },
];

export const universeEdges: UniverseEdge[] = [
  // SNL → cast & creators
  { source: 'snl', target: 'bill-murray', relation: 'Cast member', strength: 5 },
  { source: 'snl', target: 'dan-aykroyd', relation: 'Cast member and writer', strength: 5 },
  { source: 'snl', target: 'eddie-murphy', relation: 'Cast member', strength: 5 },
  { source: 'snl', target: 'tina-fey', relation: 'Head writer and cast', strength: 5 },
  { source: 'snl', target: 'amy-poehler', relation: 'Cast and Update anchor', strength: 5 },
  { source: 'snl', target: 'maya-rudolph', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'adam-sandler', relation: 'Cast member and writer', strength: 4 },
  { source: 'snl', target: 'chris-rock', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'andy-samberg', relation: 'Digital shorts', strength: 4 },
  { source: 'snl', target: 'kristen-wiig', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'will-ferrell', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'chevy-chase', relation: 'Original cast member', strength: 5 },
  { source: 'snl', target: 'john-belushi', relation: 'Original cast member', strength: 5 },
  { source: 'snl', target: 'gilda-radner', relation: 'Original cast member', strength: 5 },
  { source: 'snl', target: 'dana-carvey', relation: 'Cast member', strength: 5 },
  { source: 'snl', target: 'mike-myers', relation: 'Cast member and writer', strength: 5 },
  { source: 'snl', target: 'molly-shannon', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'jimmy-fallon', relation: 'Cast and Update anchor', strength: 4 },
  { source: 'snl', target: 'seth-meyers', relation: 'Head writer and Update anchor', strength: 5 },
  { source: 'snl', target: 'bill-hader', relation: 'Cast member', strength: 5 },
  { source: 'snl', target: 'kate-mckinnon', relation: 'Cast member', strength: 5 },
  { source: 'snl', target: 'kenan-thompson', relation: 'Longest-serving cast member', strength: 5 },
  { source: 'snl', target: 'fred-armisen', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'lorne-michaels', relation: 'Created and produced', strength: 5 },
  { source: 'snl', target: 'phil-hartman', relation: 'Cast member', strength: 5 },
  { source: 'snl', target: 'chris-farley', relation: 'Cast member', strength: 5 },
  { source: 'snl', target: 'david-spade', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'norm-macdonald', relation: 'Cast and Update anchor', strength: 4 },
  { source: 'snl', target: 'julia-louis-dreyfus', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'billy-crystal', relation: 'Cast member', strength: 3 },
  { source: 'snl', target: 'martin-short', relation: 'Cast member', strength: 3 },
  { source: 'snl', target: 'jon-lovitz', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'will-forte', relation: 'Cast member and writer', strength: 4 },
  { source: 'snl', target: 'jason-sudeikis', relation: 'Cast member and writer', strength: 4 },
  { source: 'snl', target: 'pete-davidson', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'cecily-strong', relation: 'Cast and Update character', strength: 4 },
  { source: 'snl', target: 'aidy-bryant', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'bowen-yang', relation: 'Cast member and writer', strength: 4 },
  { source: 'snl', target: 'tracy-morgan', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'darrell-hammond', relation: 'Cast member and announcer', strength: 4 },
  { source: 'snl', target: 'rachel-dratch', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'tim-robinson', relation: 'Cast member and writer', strength: 3 },
  { source: 'snl', target: 'bobby-moynihan', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'kevin-nealon', relation: 'Cast and Update anchor', strength: 4 },
  { source: 'snl', target: 'colin-jost', relation: 'Head writer and Update anchor', strength: 4 },
  { source: 'snl', target: 'michael-che', relation: 'Head writer and Update anchor', strength: 4 },
  { source: 'snl', target: 'john-mulaney', relation: 'Writer and recurring host', strength: 4 },
  { source: 'snl', target: 'robert-smigel', relation: 'Writer and animator', strength: 4 },
  { source: 'snl', target: 'conan-obrien', relation: 'Former writer', strength: 3 },

  // Lorne Michaels productions / mentorship
  { source: 'lorne-michaels', target: 'thirty-rock', relation: 'Produced', strength: 4 },
  { source: 'lorne-michaels', target: 'mean-girls', relation: 'Produced', strength: 4 },
  { source: 'lorne-michaels', target: 'tonight-show', relation: 'Executive produced', strength: 4 },
  { source: 'lorne-michaels', target: 'late-night-seth', relation: 'Executive produced', strength: 4 },
  { source: 'lorne-michaels', target: 'documentary-now', relation: 'Executive produced', strength: 3 },
  { source: 'lorne-michaels', target: 'andy-samberg', relation: 'Produced digital era projects', strength: 3 },

  // Original era films
  { source: 'bill-murray', target: 'dan-aykroyd', relation: 'Co-starred', project: 'Ghostbusters', strength: 5 },
  { source: 'bill-murray', target: 'ghostbusters', relation: 'Starred in', strength: 5 },
  { source: 'bill-murray', target: 'caddyshack', relation: 'Starred in', strength: 5 },
  { source: 'bill-murray', target: 'stripes', relation: 'Starred in', strength: 4 },
  { source: 'bill-murray', target: 'groundhog-day', relation: 'Starred in', strength: 5 },
  { source: 'dan-aykroyd', target: 'ghostbusters', relation: 'Co-wrote and starred', strength: 5 },
  { source: 'dan-aykroyd', target: 'blues-brothers', relation: 'Co-created and starred', strength: 5 },
  { source: 'dan-aykroyd', target: 'trading-places', relation: 'Starred in', strength: 4 },
  { source: 'dan-aykroyd', target: 'coneheads-movie', relation: 'Starred in', strength: 4 },
  { source: 'john-belushi', target: 'blues-brothers', relation: 'Co-created and starred', strength: 5 },
  { source: 'john-belushi', target: 'animal-house', relation: 'Starred in', strength: 5 },
  { source: 'john-belushi', target: 'dan-aykroyd', relation: 'Creative partners', project: 'The Blues Brothers', strength: 5 },
  { source: 'chevy-chase', target: 'caddyshack', relation: 'Starred in', strength: 5 },
  { source: 'chevy-chase', target: 'bill-murray', relation: 'Co-starred', project: 'Caddyshack', strength: 4 },
  { source: 'chevy-chase', target: 'three-amigos', relation: 'Starred in', strength: 4 },
  { source: 'martin-short', target: 'three-amigos', relation: 'Starred in', strength: 4 },
  { source: 'chevy-chase', target: 'martin-short', relation: 'Co-starred', project: 'Three Amigos', strength: 3 },

  // Harold Ramis film bridge
  { source: 'harold-ramis', target: 'ghostbusters', relation: 'Co-wrote and starred', strength: 5 },
  { source: 'harold-ramis', target: 'caddyshack', relation: 'Co-wrote and directed', strength: 5 },
  { source: 'harold-ramis', target: 'stripes', relation: 'Co-wrote and starred', strength: 4 },
  { source: 'harold-ramis', target: 'groundhog-day', relation: 'Directed', strength: 5 },
  { source: 'harold-ramis', target: 'bill-murray', relation: 'Frequent collaborators', strength: 4 },

  // Eddie Murphy films & characters
  { source: 'eddie-murphy', target: 'beverly-hills-cop', relation: 'Starred in', strength: 5 },
  { source: 'eddie-murphy', target: 'coming-to-america', relation: 'Starred in multiple roles', strength: 5 },
  { source: 'eddie-murphy', target: 'trading-places', relation: 'Starred in', strength: 4 },
  { source: 'eddie-murphy', target: 'shrek', relation: 'Voiced Donkey', strength: 4 },
  { source: 'eddie-murphy', target: 'gumby', relation: 'Performed character', strength: 5 },
  { source: 'eddie-murphy', target: 'mr-robinson', relation: 'Performed character', strength: 5 },
  { source: 'gumby', target: 'snl', relation: 'Recurring character', strength: 4 },
  { source: 'mr-robinson', target: 'snl', relation: 'Recurring character', strength: 4 },

  // Carvey / Myers / Wayne's World
  { source: 'dana-carvey', target: 'mike-myers', relation: 'Sketch partners', project: 'Wayne’s World', strength: 5 },
  { source: 'dana-carvey', target: 'waynes-world', relation: 'Starred in', strength: 5 },
  { source: 'mike-myers', target: 'waynes-world', relation: 'Created and starred', strength: 5 },
  { source: 'mike-myers', target: 'austin-powers', relation: 'Created and starred', strength: 5 },
  { source: 'mike-myers', target: 'shrek', relation: 'Voiced Shrek', strength: 5 },
  { source: 'mike-myers', target: 'wayne-campbell', relation: 'Performed character', strength: 5 },
  { source: 'wayne-campbell', target: 'waynes-world', relation: 'Film adaptation', strength: 5 },
  { source: 'dana-carvey', target: 'church-lady', relation: 'Performed character', strength: 5 },
  { source: 'church-lady', target: 'snl', relation: 'Recurring character', strength: 4 },
  { source: 'dana-carvey', target: 'hans-and-franz', relation: 'Performed character', strength: 4 },
  { source: 'kevin-nealon', target: 'hans-and-franz', relation: 'Performed character', strength: 4 },
  { source: 'dana-carvey', target: 'kevin-nealon', relation: 'Sketch partners', project: 'Hans and Franz', strength: 4 },
  { source: 'mike-myers', target: 'eddie-murphy', relation: 'Co-led franchise', project: 'Shrek', strength: 4 },

  // Fey / Poehler / 30 Rock / Parks
  { source: 'tina-fey', target: 'amy-poehler', relation: 'Update partners and co-stars', strength: 5 },
  { source: 'tina-fey', target: 'thirty-rock', relation: 'Created and starred', strength: 5 },
  { source: 'tina-fey', target: 'mean-girls', relation: 'Wrote and appeared', strength: 5 },
  { source: 'tina-fey', target: 'baby-mama', relation: 'Starred in', strength: 4 },
  { source: 'tina-fey', target: 'sisters', relation: 'Starred in', strength: 4 },
  { source: 'amy-poehler', target: 'baby-mama', relation: 'Starred in', strength: 4 },
  { source: 'amy-poehler', target: 'sisters', relation: 'Starred in', strength: 4 },
  { source: 'amy-poehler', target: 'parks-rec', relation: 'Starred in', strength: 5 },
  { source: 'amy-poehler', target: 'maya-rudolph', relation: 'Frequent collaborators', strength: 4 },
  { source: 'tracy-morgan', target: 'thirty-rock', relation: 'Starred in', strength: 5 },
  { source: 'tina-fey', target: 'tracy-morgan', relation: 'Reunited on 30 Rock', strength: 4 },

  // Wiig / Rudolph / Bridesmaids
  { source: 'maya-rudolph', target: 'bridesmaids', relation: 'Starred in', strength: 5 },
  { source: 'maya-rudolph', target: 'big-mouth', relation: 'Voice role', strength: 4 },
  { source: 'kristen-wiig', target: 'bridesmaids', relation: 'Co-wrote and starred', strength: 5 },
  { source: 'kristen-wiig', target: 'maya-rudolph', relation: 'Co-starred', project: 'Bridesmaids', strength: 5 },
  { source: 'kristen-wiig', target: 'target-lady', relation: 'Performed character', strength: 4 },
  { source: 'target-lady', target: 'snl', relation: 'Recurring character', strength: 3 },
  { source: 'kristen-wiig', target: 'macgruber-movie', relation: 'Co-starred', strength: 4 },

  // Molly Shannon / Superstar
  { source: 'molly-shannon', target: 'mary-katherine-gallagher', relation: 'Performed character', strength: 5 },
  { source: 'mary-katherine-gallagher', target: 'superstar', relation: 'Film adaptation', strength: 5 },
  { source: 'molly-shannon', target: 'superstar', relation: 'Starred in', strength: 5 },

  // Update lineage
  { source: 'jimmy-fallon', target: 'tina-fey', relation: 'Weekend Update anchors', strength: 4 },
  { source: 'jimmy-fallon', target: 'tonight-show', relation: 'Hosts', strength: 5 },
  { source: 'seth-meyers', target: 'amy-poehler', relation: 'Weekend Update anchors', strength: 4 },
  { source: 'seth-meyers', target: 'late-night-seth', relation: 'Hosts', strength: 5 },
  { source: 'seth-meyers', target: 'bill-hader', relation: 'Update collaborators', project: 'Stefon', strength: 4 },
  { source: 'colin-jost', target: 'michael-che', relation: 'Update co-anchors', strength: 5 },
  { source: 'colin-jost', target: 'seth-meyers', relation: 'Update desk lineage', strength: 3 },
  { source: 'norm-macdonald', target: 'colin-jost', relation: 'Update desk lineage', strength: 2 },

  // Hader / Stefon / Mulaney / Barry / Documentary Now
  { source: 'bill-hader', target: 'stefon', relation: 'Performed character', strength: 5 },
  { source: 'stefon', target: 'snl', relation: 'Recurring character', strength: 4 },
  { source: 'john-mulaney', target: 'stefon', relation: 'Co-created character', strength: 5 },
  { source: 'john-mulaney', target: 'bill-hader', relation: 'Writing partners', project: 'Stefon', strength: 4 },
  { source: 'bill-hader', target: 'barry', relation: 'Co-created and starred', strength: 5 },
  { source: 'bill-hader', target: 'documentary-now', relation: 'Co-created and starred', strength: 4 },
  { source: 'fred-armisen', target: 'documentary-now', relation: 'Co-created and starred', strength: 4 },
  { source: 'seth-meyers', target: 'documentary-now', relation: 'Co-created', strength: 3 },
  { source: 'fred-armisen', target: 'bill-hader', relation: 'Co-created', project: 'Documentary Now!', strength: 4 },
  { source: 'fred-armisen', target: 'portlandia', relation: 'Co-created and starred', strength: 5 },

  // Sandler ecosystem
  { source: 'adam-sandler', target: 'billy-madison', relation: 'Starred in', strength: 5 },
  { source: 'adam-sandler', target: 'happy-gilmore', relation: 'Starred in', strength: 5 },
  { source: 'adam-sandler', target: 'grown-ups', relation: 'Co-wrote and starred', strength: 4 },
  { source: 'adam-sandler', target: 'chris-rock', relation: 'Co-starred', project: 'Grown Ups', strength: 4 },
  { source: 'adam-sandler', target: 'david-spade', relation: 'Co-starred', project: 'Grown Ups', strength: 4 },
  { source: 'chris-rock', target: 'grown-ups', relation: 'Starred in', strength: 4 },
  { source: 'chris-rock', target: 'eddie-murphy', relation: 'Stand-up and film lineage', strength: 3 },
  { source: 'david-spade', target: 'grown-ups', relation: 'Starred in', strength: 4 },

  // Farley & Spade
  { source: 'chris-farley', target: 'matt-foley', relation: 'Performed character', strength: 5 },
  { source: 'matt-foley', target: 'snl', relation: 'Recurring character', strength: 4 },
  { source: 'chris-farley', target: 'tommy-boy', relation: 'Starred in', strength: 5 },
  { source: 'david-spade', target: 'tommy-boy', relation: 'Starred in', strength: 5 },
  { source: 'chris-farley', target: 'david-spade', relation: 'Comedy duo', project: 'Tommy Boy', strength: 5 },

  // Ferrell films
  { source: 'will-ferrell', target: 'anchorman', relation: 'Co-wrote and starred', strength: 5 },
  { source: 'will-ferrell', target: 'talladega-nights', relation: 'Co-wrote and starred', strength: 5 },
  { source: 'will-ferrell', target: 'step-brothers', relation: 'Starred in', strength: 4 },
  { source: 'will-ferrell', target: 'elf', relation: 'Starred in', strength: 4 },
  { source: 'will-ferrell', target: 'kristen-wiig', relation: 'SNL ensemble lineage', strength: 3 },

  // Forte
  { source: 'will-forte', target: 'macgruber', relation: 'Performed character', strength: 5 },
  { source: 'macgruber', target: 'snl', relation: 'Recurring character', strength: 4 },
  { source: 'will-forte', target: 'macgruber-movie', relation: 'Co-wrote and starred', strength: 5 },
  { source: 'macgruber', target: 'macgruber-movie', relation: 'Film adaptation', strength: 5 },
  { source: 'will-forte', target: 'last-man-earth', relation: 'Created and starred', strength: 5 },

  // Aykroyd Coneheads
  { source: 'coneheads-movie', target: 'snl', relation: 'Sketch-to-film', strength: 3 },

  // Hartman
  { source: 'phil-hartman', target: 'unfrozen-caveman-lawyer', relation: 'Performed character', strength: 5 },
  { source: 'unfrozen-caveman-lawyer', target: 'snl', relation: 'Recurring character', strength: 4 },
  { source: 'phil-hartman', target: 'newsradio', relation: 'Starred in', strength: 5 },

  // Gilda
  { source: 'gilda-radner', target: 'roseanne-roseannadanna', relation: 'Performed character', strength: 5 },
  { source: 'roseanne-roseannadanna', target: 'snl', relation: 'Weekend Update character', strength: 4 },

  // Lovitz / Short / Crystal
  { source: 'billy-crystal', target: 'when-harry-met-sally', relation: 'Starred in', strength: 5 },
  { source: 'martin-short', target: 'ed-grimley', relation: 'Performed character', strength: 5 },
  { source: 'ed-grimley', target: 'snl', relation: 'Recurring character', strength: 4 },

  // JLD
  { source: 'julia-louis-dreyfus', target: 'seinfeld', relation: 'Starred in', strength: 5 },
  { source: 'julia-louis-dreyfus', target: 'veep', relation: 'Starred in', strength: 5 },

  // Sudeikis
  { source: 'jason-sudeikis', target: 'ted-lasso', relation: 'Co-created and starred', strength: 5 },

  // Dratch
  { source: 'rachel-dratch', target: 'debbie-downer', relation: 'Performed character', strength: 5 },
  { source: 'debbie-downer', target: 'snl', relation: 'Recurring character', strength: 4 },
  { source: 'rachel-dratch', target: 'thirty-rock', relation: 'Recurring role', strength: 3 },

  // Moynihan / Strong / Davidson / modern
  { source: 'bobby-moynihan', target: 'drunk-uncle', relation: 'Performed character', strength: 5 },
  { source: 'drunk-uncle', target: 'snl', relation: 'Weekend Update character', strength: 4 },
  { source: 'cecily-strong', target: 'the-girl-you-wish', relation: 'Performed character', strength: 5 },
  { source: 'the-girl-you-wish', target: 'snl', relation: 'Weekend Update character', strength: 4 },
  { source: 'cecily-strong', target: 'schmigadoon', relation: 'Starred in', strength: 5 },
  { source: 'pete-davidson', target: 'king-of-staten-island', relation: 'Co-wrote and starred', strength: 5 },
  { source: 'aidy-bryant', target: 'cecily-strong', relation: '2010s cast partners', strength: 3 },
  { source: 'bowen-yang', target: 'aidy-bryant', relation: '2010s-2020s cast overlap', strength: 3 },

  // Samberg
  { source: 'andy-samberg', target: 'brooklyn-nine-nine', relation: 'Starred in', strength: 5 },
  { source: 'andy-samberg', target: 'popstar', relation: 'Co-wrote and starred', strength: 5 },
  { source: 'andy-samberg', target: 'hot-rod', relation: 'Starred in', strength: 4 },

  // Kenan
  { source: 'kenan-thompson', target: 'what-up-with-that', relation: 'Performed character', strength: 5 },
  { source: 'what-up-with-that', target: 'snl', relation: 'Recurring sketch', strength: 4 },
  { source: 'kenan-thompson', target: 'kenan-show', relation: 'Starred in', strength: 5 },

  // Tim Robinson
  { source: 'tim-robinson', target: 'i-think-you-should-leave', relation: 'Created and starred', strength: 5 },

  // Cross-era cast lineages
  { source: 'kate-mckinnon', target: 'bill-hader', relation: 'Impressionist lineage', strength: 3 },
  { source: 'kate-mckinnon', target: 'kenan-thompson', relation: '2010s cast overlap', strength: 4 },
  { source: 'darrell-hammond', target: 'phil-hartman', relation: 'Impressionist lineage', strength: 3 },
  { source: 'jon-lovitz', target: 'phil-hartman', relation: '80s cast partners', strength: 3 },

  // Robert Smigel / Conan
  { source: 'robert-smigel', target: 'conan-obrien', relation: 'Writing partners', strength: 3 },

  // Award connections
  { source: 'tina-fey', target: 'emmy-award', relation: 'Multiple wins', strength: 4 },
  { source: 'bill-hader', target: 'emmy-award', relation: 'Multiple wins', project: 'Barry', strength: 4 },
  { source: 'kate-mckinnon', target: 'emmy-award', relation: 'Multiple wins', strength: 4 },
  { source: 'julia-louis-dreyfus', target: 'emmy-award', relation: 'Record wins', strength: 5 },
  { source: 'jason-sudeikis', target: 'emmy-award', relation: 'Wins', project: 'Ted Lasso', strength: 3 },
  { source: 'maya-rudolph', target: 'emmy-award', relation: 'Wins', strength: 3 },
  { source: 'tina-fey', target: 'mark-twain-prize', relation: 'Honoree', strength: 4 },
  { source: 'eddie-murphy', target: 'mark-twain-prize', relation: 'Honoree', strength: 4 },
  { source: 'will-ferrell', target: 'mark-twain-prize', relation: 'Honoree', strength: 4 },
  { source: 'julia-louis-dreyfus', target: 'mark-twain-prize', relation: 'Honoree', strength: 3 },
  { source: 'adam-sandler', target: 'mark-twain-prize', relation: 'Honoree', strength: 3 },
  { source: 'shrek', target: 'academy-award', relation: 'Won Best Animated Feature', strength: 4 },
  { source: 'kristen-wiig', target: 'academy-award', relation: 'Screenplay nomination', project: 'Bridesmaids', strength: 3 },
];

export const timelineMoments: TimelineMoment[] = [
  {
    year: '1975',
    title: 'The original live experiment begins',
    detail: 'SNL launches a new grammar for late-night sketch comedy and immediately creates a reusable talent pipeline.',
    era: 'Original cast',
  },
  {
    year: '1978',
    title: 'Animal House proves the movie pull',
    detail: 'John Belushi becomes a film star mid-run, signaling that SNL could mint Hollywood headliners.',
    era: 'Original cast',
  },
  {
    year: '1980',
    title: 'Eddie Murphy changes the center of gravity',
    detail: 'The early-80s reset produces a star whose characters and stand-up voice carry the show into a new decade.',
    era: 'Rebuild',
  },
  {
    year: '1984',
    title: 'Ghostbusters proves the movie bridge',
    detail: 'Bill Murray and Dan Aykroyd help define how SNL alumni can move from sketches into blockbuster worlds.',
    era: 'Film crossover',
  },
  {
    year: '1992',
    title: 'Wayne’s World tops the box office',
    detail: 'Mike Myers and Dana Carvey turn a recurring sketch into the most successful SNL film to date.',
    era: 'Sketch-to-film boom',
  },
  {
    year: '1995',
    title: 'The Bad Boys era hits the movies',
    detail: 'Sandler, Farley, Spade, and Rock spin SNL personas into a 1990s comedy-film ecosystem.',
    era: 'Bad Boys era',
  },
  {
    year: '1997',
    title: 'Tina Fey enters the writers room',
    detail: 'A future head writer and Update anchor helps shape the voice of the late-90s and 2000s show.',
    era: 'Writer-producer era',
  },
  {
    year: '2004',
    title: 'Mean Girls extends the writers room',
    detail: 'Tina Fey turns SNL writing instincts into a quotable film that becomes a multi-generational phenomenon.',
    era: 'Writer-producer era',
  },
  {
    year: '2005',
    title: 'Digital shorts go viral',
    detail: 'Andy Samberg and The Lonely Island make the web feel like a native SNL stage.',
    era: 'Digital era',
  },
  {
    year: '2011',
    title: 'Bridesmaids expands the ensemble map',
    detail: 'Kristen Wiig and Maya Rudolph connect SNL character work to a major modern comedy ensemble.',
    era: 'Modern ensemble',
  },
  {
    year: '2018',
    title: 'Prestige TV claims the alumni',
    detail: 'Bill Hader’s Barry shows how SNL performers now anchor prestige comedy-drama, not just sketch and studio films.',
    era: 'Prestige era',
  },
  {
    year: '2021',
    title: 'A streaming-era comedy diaspora',
    detail: 'From Ted Lasso to I Think You Should Leave, alumni define comedy across every streaming platform at once.',
    era: 'Streaming era',
  },
];

export const triviaQuestions: TriviaQuestion[] = [
  {
    prompt: 'Which SNL alum wrote Mean Girls and later created 30 Rock?',
    answer: 'Tina Fey',
    options: ['Tina Fey', 'Amy Poehler', 'Kristen Wiig'],
  },
  {
    prompt: 'Which movie connects Bill Murray and Dan Aykroyd in this universe?',
    answer: 'Ghostbusters',
    options: ['Ghostbusters', 'Bridesmaids', 'Mean Girls'],
  },
  {
    prompt: 'Which recurring Weekend Update character is famous for absurd nightlife recommendations?',
    answer: 'Stefon',
    options: ['Stefon', 'Gumby', 'Target Lady'],
  },
  {
    prompt: 'Which buddy comedy paired Chris Farley and David Spade after their SNL run?',
    answer: 'Tommy Boy',
    options: ['Tommy Boy', 'Grown Ups', 'Step Brothers'],
  },
  {
    prompt: 'Which two SNL alumni voiced the leads in Shrek?',
    answer: 'Mike Myers and Eddie Murphy',
    options: ['Mike Myers and Eddie Murphy', 'Will Ferrell and Adam Sandler', 'Dan Aykroyd and Chevy Chase'],
  },
  {
    prompt: 'Which Chris Farley character lived "in a van down by the river"?',
    answer: 'Matt Foley',
    options: ['Matt Foley', 'Mr. Robinson', 'Drunk Uncle'],
  },
  {
    prompt: 'Which SNL alum co-created and starred in the prestige series Barry?',
    answer: 'Bill Hader',
    options: ['Bill Hader', 'Fred Armisen', 'Seth Meyers'],
  },
  {
    prompt: 'Which director never joined SNL but co-wrote Ghostbusters, Caddyshack, and Stripes?',
    answer: 'Harold Ramis',
    options: ['Harold Ramis', 'Lorne Michaels', 'Robert Smigel'],
  },
  {
    prompt: 'Which SNL alum went on to win a record number of acting Emmys, partly for Veep?',
    answer: 'Julia Louis-Dreyfus',
    options: ['Julia Louis-Dreyfus', 'Maya Rudolph', 'Kate McKinnon'],
  },
];
