export type UniverseNodeType = 'alumni' | 'movie' | 'tv' | 'character' | 'creator' | 'award';

export type UniverseNode = {
  id: string;
  name: string;
  type: UniverseNodeType;
  years?: string;
  role?: string;
  bio: string;
  imageTone: string;
  tags: string[];
  highlights: string[];
  catchphrases?: string[];
  awards?: string[];
};

export type UniverseEdge = {
  source: string;
  target: string;
  relation: string;
  project?: string;
  strength: number;
};

export type TimelineMoment = {
  year: string;
  title: string;
  detail: string;
  era: string;
};

export const universeNodes: UniverseNode[] = [
  {
    id: 'snl',
    name: 'Saturday Night Live',
    type: 'tv',
    years: '1975-present',
    role: 'NBC sketch institution',
    bio: 'The live comedy engine that connects generations of performers, writers, hosts, musicians, and recurring characters.',
    imageTone: 'from-slate-900 via-red-700 to-amber-300',
    tags: ['Sketches', 'Weekend Update', 'Live TV'],
    highlights: ['Late-night comedy launchpad', 'Political satire archive', 'Recurring character factory'],
  },
  {
    id: 'bill-murray',
    name: 'Bill Murray',
    type: 'alumni',
    years: '1977-1980',
    role: 'Cast member',
    bio: 'Deadpan SNL star who became a film icon through comedy, melancholy, and collaborations spanning Ghostbusters to Wes Anderson.',
    imageTone: 'from-sky-800 via-cyan-600 to-amber-200',
    tags: ['Deadpan', 'Film icon', 'Original era'],
    highlights: ['Nick the Lounge Singer', 'Ghostbusters', 'Lost in Translation'],
    catchphrases: ['No one will ever believe you.'],
    awards: ['Emmy Award', 'Golden Globe'],
  },
  {
    id: 'dan-aykroyd',
    name: 'Dan Aykroyd',
    type: 'alumni',
    years: '1975-1979',
    role: 'Cast member and writer',
    bio: 'Original cast powerhouse whose characters and genre instincts helped bridge SNL sketches and blockbuster comedy.',
    imageTone: 'from-indigo-950 via-blue-600 to-lime-300',
    tags: ['Original cast', 'Writer', 'Blues Brothers'],
    highlights: ['Coneheads', 'The Blues Brothers', 'Ghostbusters'],
    awards: ['Emmy Award'],
  },
  {
    id: 'eddie-murphy',
    name: 'Eddie Murphy',
    type: 'alumni',
    years: '1980-1984',
    role: 'Cast member',
    bio: 'A breakout force who reshaped the early 1980s cast and carried SNL energy into stand-up, film, and character comedy.',
    imageTone: 'from-purple-950 via-fuchsia-700 to-yellow-300',
    tags: ['Character comedy', 'Stand-up', 'Movie star'],
    highlights: ['Mister Robinson', 'Gumby', 'Beverly Hills Cop'],
    catchphrases: ['I am Gumby.'],
    awards: ['Emmy Award', 'Golden Globe'],
  },
  {
    id: 'tina-fey',
    name: 'Tina Fey',
    type: 'alumni',
    years: '1997-2006',
    role: 'Writer, head writer, cast member',
    bio: 'Head writer and Weekend Update anchor whose SNL voice expanded into sitcoms, films, political impressions, and producer-led comedy.',
    imageTone: 'from-emerald-950 via-teal-600 to-rose-300',
    tags: ['Head writer', 'Weekend Update', 'Producer'],
    highlights: ['Weekend Update', '30 Rock', 'Mean Girls'],
    catchphrases: ['I want to go to there.'],
    awards: ['Emmy Awards', 'Mark Twain Prize'],
  },
  {
    id: 'amy-poehler',
    name: 'Amy Poehler',
    type: 'alumni',
    years: '2001-2008',
    role: 'Cast member and Weekend Update anchor',
    bio: 'High-energy performer and improviser whose SNL run connects to Upright Citizens Brigade, Parks and Recreation, and broad ensemble comedy.',
    imageTone: 'from-red-950 via-orange-600 to-cyan-200',
    tags: ['Improv', 'Weekend Update', 'Ensemble comedy'],
    highlights: ['Weekend Update', 'Parks and Recreation', 'Baby Mama'],
    awards: ['Golden Globe'],
  },
  {
    id: 'maya-rudolph',
    name: 'Maya Rudolph',
    type: 'alumni',
    years: '2000-2007',
    role: 'Cast member',
    bio: 'A musical, elastic performer with a rare range across impressions, ensemble films, voice work, and prestige comedy.',
    imageTone: 'from-zinc-900 via-pink-700 to-green-300',
    tags: ['Impressions', 'Music', 'Voice acting'],
    highlights: ['Donatella Versace', 'Bridesmaids', 'Big Mouth'],
    awards: ['Emmy Awards'],
  },
  {
    id: 'adam-sandler',
    name: 'Adam Sandler',
    type: 'alumni',
    years: '1990-1995',
    role: 'Cast member and writer',
    bio: 'Musical sketch oddball turned box-office comedy anchor, with a collaboration network that became its own comedy ecosystem.',
    imageTone: 'from-blue-950 via-violet-700 to-orange-300',
    tags: ['Songs', '90s cast', 'Film franchise'],
    highlights: ['The Chanukah Song', 'Happy Gilmore', 'Grown Ups'],
    catchphrases: ['The price is wrong.'],
    awards: ['Independent Spirit Award'],
  },
  {
    id: 'chris-rock',
    name: 'Chris Rock',
    type: 'alumni',
    years: '1990-1993',
    role: 'Cast member',
    bio: 'Sharp stand-up voice whose SNL orbit links political comedy, film ensembles, HBO specials, and modern comedy influence.',
    imageTone: 'from-stone-950 via-red-800 to-sky-300',
    tags: ['Stand-up', 'Commentary', 'Film'],
    highlights: ['New Jack City', 'Everybody Hates Chris', 'Grown Ups'],
    awards: ['Emmy Awards', 'Grammy Awards'],
  },
  {
    id: 'andy-samberg',
    name: 'Andy Samberg',
    type: 'alumni',
    years: '2005-2012',
    role: 'Cast member and digital short creator',
    bio: 'Digital-era star who helped make SNL clips native to the internet, then carried that rhythm into sitcoms and music comedy.',
    imageTone: 'from-cyan-950 via-blue-500 to-yellow-200',
    tags: ['Digital shorts', 'Music comedy', 'Brooklyn Nine-Nine'],
    highlights: ['Lazy Sunday', 'The Lonely Island', 'Brooklyn Nine-Nine'],
    awards: ['Golden Globe', 'Emmy Award'],
  },
  {
    id: 'kristen-wiig',
    name: 'Kristen Wiig',
    type: 'alumni',
    years: '2005-2012',
    role: 'Cast member',
    bio: 'Character-driven performer who turned awkwardness, commitment, and ensemble chemistry into a modern SNL signature.',
    imageTone: 'from-neutral-950 via-emerald-700 to-pink-200',
    tags: ['Characters', 'Film writing', 'Ensemble'],
    highlights: ['Target Lady', 'Bridesmaids', 'MacGruber'],
    awards: ['Oscar nomination', 'Emmy nominations'],
  },
  {
    id: 'will-ferrell',
    name: 'Will Ferrell',
    type: 'alumni',
    years: '1995-2002',
    role: 'Cast member',
    bio: 'A maximalist sketch performer whose SNL characters fed directly into a run of dominant studio comedies.',
    imageTone: 'from-amber-950 via-red-600 to-sky-200',
    tags: ['Physical comedy', 'Characters', 'Studio comedy'],
    highlights: ['Celebrity Jeopardy', 'More Cowbell', 'Anchorman'],
    catchphrases: ['More cowbell.'],
    awards: ['Mark Twain Prize'],
  },
  {
    id: 'chevy-chase',
    name: 'Chevy Chase',
    type: 'alumni',
    years: '1975-1976',
    role: 'Cast member and Weekend Update anchor',
    bio: 'Original cast member whose Weekend Update persona and film career helped define the first SNL-to-movies pathway.',
    imageTone: 'from-zinc-950 via-stone-600 to-yellow-200',
    tags: ['Original cast', 'Weekend Update', 'Film comedy'],
    highlights: ['Weekend Update', 'Caddyshack', 'National Lampoons Vacation'],
    catchphrases: ['Good evening, I am Chevy Chase and you are not.'],
    awards: ['Emmy Award'],
  },
  {
    id: 'john-belushi',
    name: 'John Belushi',
    type: 'alumni',
    years: '1975-1979',
    role: 'Cast member',
    bio: 'Original cast phenomenon whose physical intensity and music-comedy work helped turn SNL characters into cultural events.',
    imageTone: 'from-neutral-950 via-red-800 to-sky-200',
    tags: ['Original cast', 'Physical comedy', 'Blues Brothers'],
    highlights: ['Samurai Futaba', 'The Blues Brothers', 'Animal House'],
  },
  {
    id: 'gilda-radner',
    name: 'Gilda Radner',
    type: 'alumni',
    years: '1975-1980',
    role: 'Cast member',
    bio: 'Beloved original cast member whose characters made emotional specificity and joyful absurdity central to SNL.',
    imageTone: 'from-rose-950 via-pink-600 to-amber-200',
    tags: ['Original cast', 'Characters', 'Sketch icon'],
    highlights: ['Roseanne Roseannadanna', 'Emily Litella', 'Baba Wawa'],
    catchphrases: ['Never mind.'],
    awards: ['Emmy Award'],
  },
  {
    id: 'dana-carvey',
    name: 'Dana Carvey',
    type: 'alumni',
    years: '1986-1993',
    role: 'Cast member',
    bio: 'Master impressionist and character comedian whose SNL run linked political satire, recurring characters, and breakout sketch films.',
    imageTone: 'from-blue-950 via-indigo-600 to-amber-200',
    tags: ['Impressions', 'Characters', 'Waynes World'],
    highlights: ['The Church Lady', 'George H. W. Bush', 'Waynes World'],
    catchphrases: ['Well, isnt that special?'],
    awards: ['Emmy Award'],
  },
  {
    id: 'mike-myers',
    name: 'Mike Myers',
    type: 'alumni',
    years: '1989-1995',
    role: 'Cast member and writer',
    bio: 'Character architect whose SNL creations became film franchises and a durable language of 1990s comedy.',
    imageTone: 'from-slate-950 via-cyan-700 to-orange-200',
    tags: ['Characters', 'Film franchise', 'Writer-performer'],
    highlights: ['Waynes World', 'Austin Powers', 'Shrek'],
    catchphrases: ['Party on.'],
  },
  {
    id: 'molly-shannon',
    name: 'Molly Shannon',
    type: 'alumni',
    years: '1995-2001',
    role: 'Cast member',
    bio: 'Fearless physical comedian whose characters helped establish the late-1990s cast as a new character-comedy engine.',
    imageTone: 'from-red-950 via-orange-600 to-pink-200',
    tags: ['Physical comedy', 'Characters', '90s cast'],
    highlights: ['Mary Katherine Gallagher', 'Superstar', 'The Delicious Dish'],
  },
  {
    id: 'jimmy-fallon',
    name: 'Jimmy Fallon',
    type: 'alumni',
    years: '1998-2004',
    role: 'Cast member and Weekend Update anchor',
    bio: 'Impressionist, musical performer, and Update anchor who later became a major late-night host.',
    imageTone: 'from-sky-950 via-blue-600 to-white',
    tags: ['Weekend Update', 'Music comedy', 'Late night'],
    highlights: ['Weekend Update', 'Barry Gibb Talk Show', 'The Tonight Show'],
    awards: ['Emmy Award'],
  },
  {
    id: 'seth-meyers',
    name: 'Seth Meyers',
    type: 'alumni',
    years: '2001-2014',
    role: 'Cast member, head writer, Weekend Update anchor',
    bio: 'Longtime writer-performer and Update anchor whose SNL voice continued into late-night political comedy.',
    imageTone: 'from-indigo-950 via-slate-600 to-cyan-200',
    tags: ['Head writer', 'Weekend Update', 'Late night'],
    highlights: ['Weekend Update', 'Really!?!', 'Late Night'],
    awards: ['Emmy Award'],
  },
  {
    id: 'bill-hader',
    name: 'Bill Hader',
    type: 'alumni',
    years: '2005-2013',
    role: 'Cast member',
    bio: 'Impressionist and character performer whose SNL work bridged surreal Update characters, cinema, and prestige comedy.',
    imageTone: 'from-violet-950 via-purple-700 to-lime-200',
    tags: ['Impressions', 'Characters', 'Prestige comedy'],
    highlights: ['Stefon', 'Vinny Vedecci', 'Barry'],
    awards: ['Emmy Awards'],
  },
  {
    id: 'kate-mckinnon',
    name: 'Kate McKinnon',
    type: 'alumni',
    years: '2012-2022',
    role: 'Cast member',
    bio: 'Transformational impressionist and character performer who became one of the defining cast members of the 2010s.',
    imageTone: 'from-teal-950 via-emerald-600 to-violet-200',
    tags: ['Impressions', 'Characters', '2010s cast'],
    highlights: ['Hillary Clinton', 'Ruth Bader Ginsburg', 'Close Encounter'],
    awards: ['Emmy Awards'],
  },
  {
    id: 'kenan-thompson',
    name: 'Kenan Thompson',
    type: 'alumni',
    years: '2003-present',
    role: 'Cast member',
    bio: 'SNLs longest-serving cast member, known for anchoring sketches across multiple eras with warmth, timing, and range.',
    imageTone: 'from-amber-950 via-yellow-700 to-cyan-200',
    tags: ['Longest-serving cast', 'Characters', 'Modern era'],
    highlights: ['What Up With That', 'Family Feud', 'Kenan'],
    awards: ['Emmy Award'],
  },
  {
    id: 'fred-armisen',
    name: 'Fred Armisen',
    type: 'alumni',
    years: '2002-2013',
    role: 'Cast member',
    bio: 'Musical and observational sketch performer whose SNL sensibility extended into Portlandia and character-driven satire.',
    imageTone: 'from-stone-950 via-emerald-800 to-rose-200',
    tags: ['Music comedy', 'Characters', 'Alternative comedy'],
    highlights: ['Fericito', 'Portlandia', 'Documentary Now!'],
    awards: ['Peabody Award'],
  },
  {
    id: 'lorne-michaels',
    name: 'Lorne Michaels',
    type: 'creator',
    years: '1975-present',
    role: 'Creator and producer',
    bio: 'The producer whose casting, writing rooms, and alumni pipeline make SNL feel like an expandable comedy universe.',
    imageTone: 'from-black via-zinc-700 to-red-300',
    tags: ['Producer', 'Talent pipeline', 'Broadway Video'],
    highlights: ['Created SNL', 'Produced 30 Rock', 'Launched generations'],
    awards: ['Emmy Awards', 'Kennedy Center Honors'],
  },
  {
    id: 'ghostbusters',
    name: 'Ghostbusters',
    type: 'movie',
    years: '1984',
    role: 'Supernatural comedy film',
    bio: 'A major bridge from early SNL talent into blockbuster genre comedy.',
    imageTone: 'from-gray-950 via-emerald-700 to-white',
    tags: ['Film', 'Supernatural comedy', 'Franchise'],
    highlights: ['Bill Murray', 'Dan Aykroyd', 'Harold Ramis'],
  },
  {
    id: 'mean-girls',
    name: 'Mean Girls',
    type: 'movie',
    years: '2004',
    role: 'Teen comedy film',
    bio: 'Tina Fey-written comedy that extended SNL writing instincts into a quotable film and stage universe.',
    imageTone: 'from-pink-950 via-rose-500 to-white',
    tags: ['Film', 'Written by Tina Fey', 'Pop culture'],
    highlights: ['Tina Fey screenplay', 'Lorne Michaels production', 'Broadway adaptation'],
  },
  {
    id: 'thirty-rock',
    name: '30 Rock',
    type: 'tv',
    years: '2006-2013',
    role: 'Network sitcom',
    bio: 'A backstage comedy that channels SNL production culture into a rapid-fire sitcom.',
    imageTone: 'from-slate-950 via-teal-700 to-amber-200',
    tags: ['TV', 'Workplace comedy', 'NBC'],
    highlights: ['Tina Fey', 'Lorne Michaels', 'Emmy-winning sitcom'],
  },
  {
    id: 'parks-rec',
    name: 'Parks and Recreation',
    type: 'tv',
    years: '2009-2015',
    role: 'Workplace sitcom',
    bio: 'Amy Poehler-led ensemble comedy connected to SNL through performers, writers, and improv culture.',
    imageTone: 'from-green-950 via-lime-700 to-yellow-200',
    tags: ['TV', 'Ensemble', 'Workplace comedy'],
    highlights: ['Amy Poehler', 'Nick Offerman', 'Optimistic civic comedy'],
  },
  {
    id: 'bridesmaids',
    name: 'Bridesmaids',
    type: 'movie',
    years: '2011',
    role: 'Ensemble comedy film',
    bio: 'A major modern comedy ensemble connecting Kristen Wiig, Maya Rudolph, and the post-2000 SNL era.',
    imageTone: 'from-fuchsia-950 via-pink-600 to-yellow-200',
    tags: ['Film', 'Ensemble', 'Written by Kristen Wiig'],
    highlights: ['Kristen Wiig', 'Maya Rudolph', 'Oscar nominations'],
  },
  {
    id: 'caddyshack',
    name: 'Caddyshack',
    type: 'movie',
    years: '1980',
    role: 'Sports comedy film',
    bio: 'A classic comedy film connecting original SNL-era performers with Harold Ramis and early studio comedy mythology.',
    imageTone: 'from-green-950 via-lime-700 to-yellow-200',
    tags: ['Film', 'Sports comedy', '1980s comedy'],
    highlights: ['Chevy Chase', 'Bill Murray', 'Harold Ramis'],
  },
  {
    id: 'blues-brothers',
    name: 'The Blues Brothers',
    type: 'movie',
    years: '1980',
    role: 'Musical comedy film',
    bio: 'A film expansion of an SNL music-comedy act built around John Belushi and Dan Aykroyd.',
    imageTone: 'from-black via-blue-900 to-white',
    tags: ['Film', 'Music comedy', 'SNL spin-off'],
    highlights: ['John Belushi', 'Dan Aykroyd', 'Sketch-to-film'],
  },
  {
    id: 'waynes-world',
    name: 'Waynes World',
    type: 'movie',
    years: '1992',
    role: 'Sketch-based comedy film',
    bio: 'A breakout SNL sketch-to-film success centered on basement public-access hosts Wayne and Garth.',
    imageTone: 'from-slate-950 via-blue-700 to-orange-200',
    tags: ['Film', 'Sketch-to-film', '1990s comedy'],
    highlights: ['Mike Myers', 'Dana Carvey', 'Party on'],
  },
  {
    id: 'austin-powers',
    name: 'Austin Powers',
    type: 'movie',
    years: '1997',
    role: 'Spy comedy film',
    bio: 'Mike Myers-led franchise that extended his character-comedy instincts beyond SNL into global pop culture.',
    imageTone: 'from-purple-950 via-fuchsia-700 to-yellow-200',
    tags: ['Film', 'Franchise', 'Character comedy'],
    highlights: ['Mike Myers', 'Spy parody', 'Multiple roles'],
  },
  {
    id: 'superstar',
    name: 'Superstar',
    type: 'movie',
    years: '1999',
    role: 'Sketch-based comedy film',
    bio: 'Mary Katherine Gallagher moved from recurring SNL character to feature comedy.',
    imageTone: 'from-red-950 via-orange-500 to-white',
    tags: ['Film', 'Sketch-to-film', 'Character comedy'],
    highlights: ['Molly Shannon', 'Mary Katherine Gallagher', 'SNL spin-off'],
  },
  {
    id: 'portlandia',
    name: 'Portlandia',
    type: 'tv',
    years: '2011-2018',
    role: 'Sketch comedy series',
    bio: 'Fred Armisen and Carrie Brownstein built a stylized sketch universe around Pacific Northwest culture.',
    imageTone: 'from-emerald-950 via-green-700 to-pink-200',
    tags: ['TV', 'Sketch comedy', 'Alternative comedy'],
    highlights: ['Fred Armisen', 'Carrie Brownstein', 'Peabody-winning satire'],
  },
  {
    id: 'stefon',
    name: 'Stefon',
    type: 'character',
    years: '2008-2013',
    role: 'Weekend Update character',
    bio: 'Bill Hader and John Mulaney created a nightlife correspondent who became one of SNLs defining Update characters.',
    imageTone: 'from-violet-950 via-fuchsia-600 to-lime-200',
    tags: ['Character', 'Weekend Update', 'Nightlife'],
    highlights: ['Performed by Bill Hader', 'Written with John Mulaney', 'Recurring Update favorite'],
    catchphrases: ['This place has everything.'],
  },
  {
    id: 'wayne-campbell',
    name: 'Wayne Campbell',
    type: 'character',
    years: '1989-1994',
    role: 'Recurring sketch character',
    bio: 'Mike Myerss public-access metalhead host became one of SNLs most successful sketch-to-film characters.',
    imageTone: 'from-zinc-950 via-blue-700 to-amber-200',
    tags: ['Character', 'Waynes World', 'Sketch-to-film'],
    highlights: ['Performed by Mike Myers', 'Waynes World', 'Party on'],
    catchphrases: ['Party on.'],
  },
  {
    id: 'church-lady',
    name: 'The Church Lady',
    type: 'character',
    years: '1986-1990s',
    role: 'Recurring sketch character',
    bio: 'Dana Carveys judgmental Church Chat host became a signature SNL character of the late 1980s.',
    imageTone: 'from-indigo-950 via-blue-700 to-white',
    tags: ['Character', 'Dana Carvey', 'Church Chat'],
    highlights: ['Performed by Dana Carvey', 'Church Chat', 'Recurring character'],
    catchphrases: ['Well, isnt that special?'],
  },
  {
    id: 'mary-katherine-gallagher',
    name: 'Mary Katherine Gallagher',
    type: 'character',
    years: '1995-2001',
    role: 'Recurring sketch character',
    bio: 'Molly Shannons hyper-intense Catholic schoolgirl became a breakout character of the 1995 cast.',
    imageTone: 'from-rose-950 via-red-600 to-white',
    tags: ['Character', 'Molly Shannon', 'Physical comedy'],
    highlights: ['Performed by Molly Shannon', 'Superstar', '90s breakout character'],
  },
  {
    id: 'gumby',
    name: 'Gumby',
    type: 'character',
    years: '1980s',
    role: 'Recurring sketch character',
    bio: 'Eddie Murphys cigar-chomping show-business version of Gumby became one of his signature SNL characters.',
    imageTone: 'from-green-950 via-lime-600 to-yellow-200',
    tags: ['Character', 'Eddie Murphy', 'Recurring sketch'],
    highlights: ['Performed by Eddie Murphy', '1980s SNL', 'Character comedy'],
    catchphrases: ['I am Gumby.'],
  },
  {
    id: 'what-up-with-that',
    name: 'What Up With That',
    type: 'character',
    years: '2009-2010s',
    role: 'Recurring sketch format',
    bio: 'Kenan Thompsons exuberant talk-show host Diondre Cole repeatedly derails celebrity interviews with song and dance.',
    imageTone: 'from-orange-950 via-yellow-600 to-cyan-200',
    tags: ['Sketch', 'Kenan Thompson', 'Music comedy'],
    highlights: ['Performed by Kenan Thompson', 'Recurring talk-show sketch', 'Musical chaos'],
  },
];

export const universeEdges: UniverseEdge[] = [
  { source: 'snl', target: 'bill-murray', relation: 'Cast member', strength: 5 },
  { source: 'snl', target: 'dan-aykroyd', relation: 'Cast member and writer', strength: 5 },
  { source: 'snl', target: 'eddie-murphy', relation: 'Cast member', strength: 5 },
  { source: 'snl', target: 'tina-fey', relation: 'Head writer and cast', strength: 5 },
  { source: 'snl', target: 'amy-poehler', relation: 'Cast and Update anchor', strength: 5 },
  { source: 'snl', target: 'maya-rudolph', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'adam-sandler', relation: 'Cast member and writer', strength: 4 },
  { source: 'snl', target: 'chris-rock', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'andy-samberg', relation: 'Digital shorts', strength: 4 },
  { source: 'snl', target: 'kristen-wiig', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'will-ferrell', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'chevy-chase', relation: 'Original cast member', strength: 5 },
  { source: 'snl', target: 'john-belushi', relation: 'Original cast member', strength: 5 },
  { source: 'snl', target: 'gilda-radner', relation: 'Original cast member', strength: 5 },
  { source: 'snl', target: 'dana-carvey', relation: 'Cast member', strength: 5 },
  { source: 'snl', target: 'mike-myers', relation: 'Cast member and writer', strength: 5 },
  { source: 'snl', target: 'molly-shannon', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'jimmy-fallon', relation: 'Cast and Update anchor', strength: 4 },
  { source: 'snl', target: 'seth-meyers', relation: 'Head writer and Update anchor', strength: 5 },
  { source: 'snl', target: 'bill-hader', relation: 'Cast member', strength: 5 },
  { source: 'snl', target: 'kate-mckinnon', relation: 'Cast member', strength: 5 },
  { source: 'snl', target: 'kenan-thompson', relation: 'Longest-serving cast member', strength: 5 },
  { source: 'snl', target: 'fred-armisen', relation: 'Cast member', strength: 4 },
  { source: 'snl', target: 'lorne-michaels', relation: 'Created and produced', strength: 5 },
  { source: 'bill-murray', target: 'dan-aykroyd', relation: 'Co-starred', project: 'Ghostbusters', strength: 5 },
  { source: 'bill-murray', target: 'ghostbusters', relation: 'Starred in', strength: 5 },
  { source: 'bill-murray', target: 'caddyshack', relation: 'Starred in', strength: 5 },
  { source: 'dan-aykroyd', target: 'ghostbusters', relation: 'Co-wrote and starred', strength: 5 },
  { source: 'dan-aykroyd', target: 'blues-brothers', relation: 'Co-created and starred', strength: 5 },
  { source: 'john-belushi', target: 'blues-brothers', relation: 'Co-created and starred', strength: 5 },
  { source: 'john-belushi', target: 'dan-aykroyd', relation: 'Creative partners', project: 'The Blues Brothers', strength: 5 },
  { source: 'chevy-chase', target: 'caddyshack', relation: 'Starred in', strength: 5 },
  { source: 'chevy-chase', target: 'bill-murray', relation: 'Co-starred', project: 'Caddyshack', strength: 4 },
  { source: 'dana-carvey', target: 'mike-myers', relation: 'Sketch partners', project: 'Waynes World', strength: 5 },
  { source: 'dana-carvey', target: 'waynes-world', relation: 'Starred in', strength: 5 },
  { source: 'mike-myers', target: 'waynes-world', relation: 'Created and starred', strength: 5 },
  { source: 'mike-myers', target: 'austin-powers', relation: 'Created and starred', strength: 5 },
  { source: 'mike-myers', target: 'wayne-campbell', relation: 'Performed character', strength: 5 },
  { source: 'wayne-campbell', target: 'waynes-world', relation: 'Film adaptation', strength: 5 },
  { source: 'dana-carvey', target: 'church-lady', relation: 'Performed character', strength: 5 },
  { source: 'church-lady', target: 'snl', relation: 'Recurring character', strength: 4 },
  { source: 'tina-fey', target: 'amy-poehler', relation: 'Update partners and co-stars', strength: 5 },
  { source: 'tina-fey', target: 'thirty-rock', relation: 'Created and starred', strength: 5 },
  { source: 'tina-fey', target: 'mean-girls', relation: 'Wrote and appeared', strength: 5 },
  { source: 'lorne-michaels', target: 'thirty-rock', relation: 'Produced', strength: 4 },
  { source: 'lorne-michaels', target: 'mean-girls', relation: 'Produced', strength: 4 },
  { source: 'amy-poehler', target: 'parks-rec', relation: 'Starred in', strength: 5 },
  { source: 'amy-poehler', target: 'maya-rudolph', relation: 'Frequent collaborators', strength: 4 },
  { source: 'maya-rudolph', target: 'bridesmaids', relation: 'Starred in', strength: 5 },
  { source: 'molly-shannon', target: 'mary-katherine-gallagher', relation: 'Performed character', strength: 5 },
  { source: 'mary-katherine-gallagher', target: 'superstar', relation: 'Film adaptation', strength: 5 },
  { source: 'molly-shannon', target: 'superstar', relation: 'Starred in', strength: 5 },
  { source: 'kristen-wiig', target: 'bridesmaids', relation: 'Co-wrote and starred', strength: 5 },
  { source: 'kristen-wiig', target: 'maya-rudolph', relation: 'Co-starred', project: 'Bridesmaids', strength: 5 },
  { source: 'jimmy-fallon', target: 'tina-fey', relation: 'Weekend Update anchors', strength: 4 },
  { source: 'seth-meyers', target: 'amy-poehler', relation: 'Weekend Update anchors', strength: 4 },
  { source: 'seth-meyers', target: 'bill-hader', relation: 'Update collaborators', project: 'Stefon', strength: 4 },
  { source: 'bill-hader', target: 'stefon', relation: 'Performed character', strength: 5 },
  { source: 'adam-sandler', target: 'chris-rock', relation: 'Co-starred', project: 'Grown Ups', strength: 4 },
  { source: 'chris-rock', target: 'eddie-murphy', relation: 'Stand-up and film lineage', strength: 3 },
  { source: 'eddie-murphy', target: 'gumby', relation: 'Performed character', strength: 5 },
  { source: 'gumby', target: 'snl', relation: 'Recurring character', strength: 4 },
  { source: 'andy-samberg', target: 'lorne-michaels', relation: 'Produced digital era projects', strength: 3 },
  { source: 'will-ferrell', target: 'kristen-wiig', relation: 'SNL ensemble lineage', strength: 3 },
  { source: 'fred-armisen', target: 'portlandia', relation: 'Co-created and starred', strength: 5 },
  { source: 'fred-armisen', target: 'bill-hader', relation: 'Co-created', project: 'Documentary Now!', strength: 4 },
  { source: 'kate-mckinnon', target: 'bill-hader', relation: 'Impressionist lineage', strength: 3 },
  { source: 'kate-mckinnon', target: 'kenan-thompson', relation: '2010s cast overlap', strength: 4 },
  { source: 'kenan-thompson', target: 'what-up-with-that', relation: 'Performed character', strength: 5 },
  { source: 'what-up-with-that', target: 'snl', relation: 'Recurring sketch', strength: 4 },
  { source: 'stefon', target: 'snl', relation: 'Recurring character', strength: 4 },
  { source: 'stefon', target: 'andy-samberg', relation: 'Shared digital-era cast orbit', strength: 2 },
];

export const timelineMoments: TimelineMoment[] = [
  {
    year: '1975',
    title: 'The original live experiment begins',
    detail: 'SNL launches a new grammar for late-night sketch comedy and immediately creates a reusable talent pipeline.',
    era: 'Original cast',
  },
  {
    year: '1980',
    title: 'Eddie Murphy changes the center of gravity',
    detail: 'The early-80s reset produces a star whose characters and stand-up voice carry the show into a new decade.',
    era: 'Rebuild',
  },
  {
    year: '1984',
    title: 'Ghostbusters proves the movie bridge',
    detail: 'Bill Murray and Dan Aykroyd help define how SNL alumni can move from sketches into blockbuster worlds.',
    era: 'Film crossover',
  },
  {
    year: '1997',
    title: 'Tina Fey enters the writers room',
    detail: 'A future head writer and Update anchor helps shape the voice of the late-90s and 2000s show.',
    era: 'Writer-producer era',
  },
  {
    year: '2005',
    title: 'Digital shorts go viral',
    detail: 'Andy Samberg and The Lonely Island make the web feel like a native SNL stage.',
    era: 'Digital era',
  },
  {
    year: '2011',
    title: 'Bridesmaids expands the ensemble map',
    detail: 'Kristen Wiig and Maya Rudolph connect SNL character work to a major modern comedy ensemble.',
    era: 'Modern ensemble',
  },
];

export const triviaQuestions = [
  {
    prompt: 'Which SNL alum wrote Mean Girls and later created 30 Rock?',
    answer: 'Tina Fey',
    options: ['Tina Fey', 'Amy Poehler', 'Kristen Wiig'],
  },
  {
    prompt: 'Which movie connects Bill Murray and Dan Aykroyd in this seed graph?',
    answer: 'Ghostbusters',
    options: ['Ghostbusters', 'Bridesmaids', 'Mean Girls'],
  },
  {
    prompt: 'Which recurring Weekend Update character is famous for absurd nightlife recommendations?',
    answer: 'Stefon',
    options: ['Stefon', 'Gumby', 'Target Lady'],
  },
];
